/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ErrorDetails } from '../models/errorDetails.js';

/**
 * Creates an instance of CustomerManagementV2Cardtype500
 */
interface CustomerManagementV2Cardtype500 {
  /** Unique request identifier passed from end user. This identifier helps in tracing a transaction */
  RequestId?: string;
  /** Indicates overall status of the request. Allowed values: SUCCES, FAILED, PARTIAL_SUCCESS */
  Status?: string;
  Errors?: ErrorDetails[];
}

export class CustomerManagementV2Cardtype500Error extends ApiError<
  CustomerManagementV2Cardtype500
> {}
