/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV1TransactionFuelconsumption500
 */
interface FleetmanagementV1TransactionFuelconsumption500 {
  fault?: Fault;
}

export class FleetmanagementV1TransactionFuelconsumption500Error extends ApiError<
  FleetmanagementV1TransactionFuelconsumption500
> {}
