/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV1TransactionCardusagesummary401
 */
interface FleetmanagementV1TransactionCardusagesummary401 {
  fault?: Fault;
}

export class FleetmanagementV1TransactionCardusagesummary401Error extends ApiError<
  FleetmanagementV1TransactionCardusagesummary401
> {}
