/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV1UserLoggedinuser500
 */
interface FleetmanagementV1UserLoggedinuser500 {
  fault?: Fault;
}

export class FleetmanagementV1UserLoggedinuser500Error extends ApiError<
  FleetmanagementV1UserLoggedinuser500
> {}
