/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV1CustomerAccounts500
 */
interface FleetmanagementV1CustomerAccounts500 {
  fault?: Fault;
}

export class FleetmanagementV1CustomerAccounts500Error extends ApiError<
  FleetmanagementV1CustomerAccounts500
> {}
