/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV2CustomerPricelist500
 */
interface FleetmanagementV2CustomerPricelist500 {
  fault?: Fault;
}

export class FleetmanagementV2CustomerPricelist500Error extends ApiError<
  FleetmanagementV2CustomerPricelist500
> {}
