/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV1TransactionUpdateodometer401
 */
interface FleetmanagementV1TransactionUpdateodometer401 {
  fault?: Fault;
}

export class FleetmanagementV1TransactionUpdateodometer401Error extends ApiError<
  FleetmanagementV1TransactionUpdateodometer401
> {}
