/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV1UserLoggedinuser401
 */
interface FleetmanagementV1UserLoggedinuser401 {
  fault?: Fault;
}

export class FleetmanagementV1UserLoggedinuser401Error extends ApiError<
  FleetmanagementV1UserLoggedinuser401
> {}
