/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV2CustomerPricelist404
 */
interface FleetmanagementV2CustomerPricelist404 {
  fault?: Fault;
}

export class FleetmanagementV2CustomerPricelist404Error extends ApiError<
  FleetmanagementV2CustomerPricelist404
> {}
