/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV1CustomerAuditreport401
 */
interface FleetmanagementV1CustomerAuditreport401 {
  fault?: Fault;
}

export class FleetmanagementV1CustomerAuditreport401Error extends ApiError<
  FleetmanagementV1CustomerAuditreport401
> {}
