/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV1CustomerCustomer400
 */
interface FleetmanagementV1CustomerCustomer400 {
  fault?: Fault;
}

export class FleetmanagementV1CustomerCustomer400Error extends ApiError<
  FleetmanagementV1CustomerCustomer400
> {}
