/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV2CustomerCardtype404
 */
interface FleetmanagementV2CustomerCardtype404 {
  fault?: Fault;
}

export class FleetmanagementV2CustomerCardtype404Error extends ApiError<
  FleetmanagementV2CustomerCardtype404
> {}
