/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { ErrorUserAccessError } from '../models/errorUserAccessError';

/**
 * Creates an instance of FleetmanagementV1TransactionCardusagesummary403
 */
interface FleetmanagementV1TransactionCardusagesummary403 {
  Error?: ErrorUserAccessError;
}

export class FleetmanagementV1TransactionCardusagesummary403Error extends ApiError<
  FleetmanagementV1TransactionCardusagesummary403
> {}
