/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV2CustomerCardtype401
 */
interface FleetmanagementV2CustomerCardtype401 {
  fault?: Fault;
}

export class FleetmanagementV2CustomerCardtype401Error extends ApiError<
  FleetmanagementV2CustomerCardtype401
> {}
