/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV1TransactionVolumebasedbonus401
 */
interface FleetmanagementV1TransactionVolumebasedbonus401 {
  fault?: Fault;
}

export class FleetmanagementV1TransactionVolumebasedbonus401Error extends ApiError<
  FleetmanagementV1TransactionVolumebasedbonus401
> {}
