/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV1TransactionFuelconsumption400
 */
interface FleetmanagementV1TransactionFuelconsumption400 {
  fault?: Fault;
}

export class FleetmanagementV1TransactionFuelconsumption400Error extends ApiError<
  FleetmanagementV1TransactionFuelconsumption400
> {}
