/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core';
import { Fault } from '../models/fault';

/**
 * Creates an instance of FleetmanagementV1TransactionExceptions404
 */
interface FleetmanagementV1TransactionExceptions404 {
  fault?: Fault;
}

export class FleetmanagementV1TransactionExceptions404Error extends ApiError<
  FleetmanagementV1TransactionExceptions404
> {}
