/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { ErrorDetails } from '../models/errorDetails.js';

/**
 * Creates an instance of TransactionDataV1Feessummary400
 */
interface TransactionDataV1Feessummary400 {
  /** Unique request identifier passed from end user. This identifier helps in tracing a transaction */
  RequestId?: string;
  /** Indicates overall status of the request. Allowed values: SUCCES, FAILED, PARTIAL_SUCCESS */
  Status?: string;
  Errors?: ErrorDetails[];
}

export class TransactionDataV1Feessummary400Error extends ApiError<
  TransactionDataV1Feessummary400
> {}
