/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  CardUsageSummaryRequest,
  cardUsageSummaryRequestSchema,
} from '../models/cardUsageSummaryRequest';
import {
  CardUsageSummaryResponse,
  cardUsageSummaryResponseSchema,
} from '../models/cardUsageSummaryResponse';
import {
  FeeSummaryResponse,
  feeSummaryResponseSchema,
} from '../models/feeSummaryResponse';
import {
  FuelConsumptionRequest,
  fuelConsumptionRequestSchema,
} from '../models/fuelConsumptionRequest';
import {
  FuelConsumptionResponse,
  fuelConsumptionResponseSchema,
} from '../models/fuelConsumptionResponse';
import {
  MultiPricedTransactionRequest,
  multiPricedTransactionRequestSchema,
} from '../models/multiPricedTransactionRequest';
import {
  MultiPricedTransactionResponse,
  multiPricedTransactionResponseSchema,
} from '../models/multiPricedTransactionResponse';
import {
  PricedTransactionRequestV2,
  pricedTransactionRequestV2Schema,
} from '../models/pricedTransactionRequestV2';
import {
  PricedTransactionResponse,
  pricedTransactionResponseSchema,
} from '../models/pricedTransactionResponse';
import {
  PricedTransactionResponseV2,
  pricedTransactionResponseV2Schema,
} from '../models/pricedTransactionResponseV2';
import {
  PricedTransSummaryResponse,
  pricedTransSummaryResponseSchema,
} from '../models/pricedTransSummaryResponse';
import {
  PriceTransactionRequest,
  priceTransactionRequestSchema,
} from '../models/priceTransactionRequest';
import {
  PriceTransSummaryRequest,
  priceTransSummaryRequestSchema,
} from '../models/priceTransSummaryRequest';
import {
  RecentTransactionRequest,
  recentTransactionRequestSchema,
} from '../models/recentTransactionRequest';
import {
  RecentTransactionsResponse,
  recentTransactionsResponseSchema,
} from '../models/recentTransactionsResponse';
import {
  TransactionExceptionsRequest,
  transactionExceptionsRequestSchema,
} from '../models/transactionExceptionsRequest';
import {
  TransactionExceptionsResponse,
  transactionExceptionsResponseSchema,
} from '../models/transactionExceptionsResponse';
import {
  TransactionFeesRequest,
  transactionFeesRequestSchema,
} from '../models/transactionFeesRequest';
import {
  TransactionFeesResponse,
  transactionFeesResponseSchema,
} from '../models/transactionFeesResponse';
import {
  UpdateOdometerRequest,
  updateOdometerRequestSchema,
} from '../models/updateOdometerRequest';
import {
  UpdateOdometerResponse,
  updateOdometerResponseSchema,
} from '../models/updateOdometerResponse';
import {
  VolumeBasedBonusRequest,
  volumeBasedBonusRequestSchema,
} from '../models/volumeBasedBonusRequest';
import {
  VolumeBasedBonusResponse,
  volumeBasedBonusResponseSchema,
} from '../models/volumeBasedBonusResponse';
import {
  VolumeBasedPricingRequest,
  volumeBasedPricingRequestSchema,
} from '../models/volumeBasedPricingRequest';
import {
  VolumeBasedPricingResponse,
  volumeBasedPricingResponseSchema,
} from '../models/volumeBasedPricingResponse';
import { optional, string } from '../schema';
import { BaseController } from './baseController';
import { FleetmanagementV1TransactionCardusagesummary400Error } from '../errors/fleetmanagementV1TransactionCardusagesummary400Error';
import { FleetmanagementV1TransactionCardusagesummary401Error } from '../errors/fleetmanagementV1TransactionCardusagesummary401Error';
import { FleetmanagementV1TransactionCardusagesummary403Error } from '../errors/fleetmanagementV1TransactionCardusagesummary403Error';
import { FleetmanagementV1TransactionCardusagesummary404Error } from '../errors/fleetmanagementV1TransactionCardusagesummary404Error';
import { FleetmanagementV1TransactionCardusagesummary500Error } from '../errors/fleetmanagementV1TransactionCardusagesummary500Error';
import { FleetmanagementV1TransactionExceptions400Error } from '../errors/fleetmanagementV1TransactionExceptions400Error';
import { FleetmanagementV1TransactionExceptions401Error } from '../errors/fleetmanagementV1TransactionExceptions401Error';
import { FleetmanagementV1TransactionExceptions403Error } from '../errors/fleetmanagementV1TransactionExceptions403Error';
import { FleetmanagementV1TransactionExceptions404Error } from '../errors/fleetmanagementV1TransactionExceptions404Error';
import { FleetmanagementV1TransactionExceptions500Error } from '../errors/fleetmanagementV1TransactionExceptions500Error';
import { FleetmanagementV1TransactionFees400Error } from '../errors/fleetmanagementV1TransactionFees400Error';
import { FleetmanagementV1TransactionFees401Error } from '../errors/fleetmanagementV1TransactionFees401Error';
import { FleetmanagementV1TransactionFees403Error } from '../errors/fleetmanagementV1TransactionFees403Error';
import { FleetmanagementV1TransactionFees404Error } from '../errors/fleetmanagementV1TransactionFees404Error';
import { FleetmanagementV1TransactionFees500Error } from '../errors/fleetmanagementV1TransactionFees500Error';
import { FleetmanagementV1TransactionFeessummary400Error } from '../errors/fleetmanagementV1TransactionFeessummary400Error';
import { FleetmanagementV1TransactionFeessummary401Error } from '../errors/fleetmanagementV1TransactionFeessummary401Error';
import { FleetmanagementV1TransactionFeessummary403Error } from '../errors/fleetmanagementV1TransactionFeessummary403Error';
import { FleetmanagementV1TransactionFeessummary404Error } from '../errors/fleetmanagementV1TransactionFeessummary404Error';
import { FleetmanagementV1TransactionFeessummary500Error } from '../errors/fleetmanagementV1TransactionFeessummary500Error';
import { FleetmanagementV1TransactionFuelconsumption400Error } from '../errors/fleetmanagementV1TransactionFuelconsumption400Error';
import { FleetmanagementV1TransactionFuelconsumption401Error } from '../errors/fleetmanagementV1TransactionFuelconsumption401Error';
import { FleetmanagementV1TransactionFuelconsumption403Error } from '../errors/fleetmanagementV1TransactionFuelconsumption403Error';
import { FleetmanagementV1TransactionFuelconsumption404Error } from '../errors/fleetmanagementV1TransactionFuelconsumption404Error';
import { FleetmanagementV1TransactionFuelconsumption500Error } from '../errors/fleetmanagementV1TransactionFuelconsumption500Error';
import { FleetmanagementV1TransactionMultipayerspricedtransactions400Error } from '../errors/fleetmanagementV1TransactionMultipayerspricedtransactions400Error';
import { FleetmanagementV1TransactionMultipayerspricedtransactions401Error } from '../errors/fleetmanagementV1TransactionMultipayerspricedtransactions401Error';
import { FleetmanagementV1TransactionMultipayerspricedtransactions403Error } from '../errors/fleetmanagementV1TransactionMultipayerspricedtransactions403Error';
import { FleetmanagementV1TransactionMultipayerspricedtransactions404Error } from '../errors/fleetmanagementV1TransactionMultipayerspricedtransactions404Error';
import { FleetmanagementV1TransactionMultipayerspricedtransactions500Error } from '../errors/fleetmanagementV1TransactionMultipayerspricedtransactions500Error';
import { FleetmanagementV1TransactionPricedtransactions400Error } from '../errors/fleetmanagementV1TransactionPricedtransactions400Error';
import { FleetmanagementV1TransactionPricedtransactions401Error } from '../errors/fleetmanagementV1TransactionPricedtransactions401Error';
import { FleetmanagementV1TransactionPricedtransactions403Error } from '../errors/fleetmanagementV1TransactionPricedtransactions403Error';
import { FleetmanagementV1TransactionPricedtransactions404Error } from '../errors/fleetmanagementV1TransactionPricedtransactions404Error';
import { FleetmanagementV1TransactionPricedtransactions500Error } from '../errors/fleetmanagementV1TransactionPricedtransactions500Error';
import { FleetmanagementV1TransactionPricedtransactionssummary400Error } from '../errors/fleetmanagementV1TransactionPricedtransactionssummary400Error';
import { FleetmanagementV1TransactionPricedtransactionssummary401Error } from '../errors/fleetmanagementV1TransactionPricedtransactionssummary401Error';
import { FleetmanagementV1TransactionPricedtransactionssummary403Error } from '../errors/fleetmanagementV1TransactionPricedtransactionssummary403Error';
import { FleetmanagementV1TransactionPricedtransactionssummary404Error } from '../errors/fleetmanagementV1TransactionPricedtransactionssummary404Error';
import { FleetmanagementV1TransactionPricedtransactionssummary500Error } from '../errors/fleetmanagementV1TransactionPricedtransactionssummary500Error';
import { FleetmanagementV1TransactionUpdateodometer400Error } from '../errors/fleetmanagementV1TransactionUpdateodometer400Error';
import { FleetmanagementV1TransactionUpdateodometer401Error } from '../errors/fleetmanagementV1TransactionUpdateodometer401Error';
import { FleetmanagementV1TransactionUpdateodometer403Error } from '../errors/fleetmanagementV1TransactionUpdateodometer403Error';
import { FleetmanagementV1TransactionUpdateodometer404Error } from '../errors/fleetmanagementV1TransactionUpdateodometer404Error';
import { FleetmanagementV1TransactionUpdateodometer500Error } from '../errors/fleetmanagementV1TransactionUpdateodometer500Error';
import { FleetmanagementV1TransactionVolumebasedbonus400Error } from '../errors/fleetmanagementV1TransactionVolumebasedbonus400Error';
import { FleetmanagementV1TransactionVolumebasedbonus401Error } from '../errors/fleetmanagementV1TransactionVolumebasedbonus401Error';
import { FleetmanagementV1TransactionVolumebasedbonus403Error } from '../errors/fleetmanagementV1TransactionVolumebasedbonus403Error';
import { FleetmanagementV1TransactionVolumebasedbonus404Error } from '../errors/fleetmanagementV1TransactionVolumebasedbonus404Error';
import { FleetmanagementV1TransactionVolumebasedbonus500Error } from '../errors/fleetmanagementV1TransactionVolumebasedbonus500Error';
import { FleetmanagementV1TransactionVolumebasedpricing400Error } from '../errors/fleetmanagementV1TransactionVolumebasedpricing400Error';
import { FleetmanagementV1TransactionVolumebasedpricing401Error } from '../errors/fleetmanagementV1TransactionVolumebasedpricing401Error';
import { FleetmanagementV1TransactionVolumebasedpricing403Error } from '../errors/fleetmanagementV1TransactionVolumebasedpricing403Error';
import { FleetmanagementV1TransactionVolumebasedpricing404Error } from '../errors/fleetmanagementV1TransactionVolumebasedpricing404Error';
import { FleetmanagementV1TransactionVolumebasedpricing500Error } from '../errors/fleetmanagementV1TransactionVolumebasedpricing500Error';
import { TransactionDataV1Priced400Error } from '../errors/transactionDataV1Priced400Error';
import { TransactionDataV1Priced401Error } from '../errors/transactionDataV1Priced401Error';
import { TransactionDataV1Priced403Error } from '../errors/transactionDataV1Priced403Error';
import { TransactionDataV1Priced404Error } from '../errors/transactionDataV1Priced404Error';
import { TransactionDataV1Priced500Error } from '../errors/transactionDataV1Priced500Error';
import { TransactionDataV1Recent400Error } from '../errors/transactionDataV1Recent400Error';
import { TransactionDataV1Recent401Error } from '../errors/transactionDataV1Recent401Error';
import { TransactionDataV1Recent403Error } from '../errors/transactionDataV1Recent403Error';
import { TransactionDataV1Recent404Error } from '../errors/transactionDataV1Recent404Error';
import { TransactionDataV1Recent500Error } from '../errors/transactionDataV1Recent500Error';

export class TransactionController extends BaseController {
  /**
   * This API allows querying transaction data (i.e. Priced, Billed and Unbilled sales items). It
   * provides a flexible search criteria and supports paging.
   *
   *
   *
   * Transactions that are posted but not yet priced, billed or that are in error will not be returned by
   * this API. The API also supports returning Fee Items.
   *
   *
   *
   * #### Supported operations
   *
   * * Get sales items and fee transactions
   *
   * * Search by invoice status
   *
   * * Search by fixed date period
   *
   * * Search by date range
   *
   * * Search by account
   *
   * * Search by card
   *
   * * Get sales items only
   *
   * * Search by transaction Id or location
   *
   * * Search by transaction posting date
   *
   * * Search by invoice number or date
   *
   * * Search by driver name or vehicle registration number
   *
   * * Search by card group
   *
   * * Search by fuel only transactions
   *
   * * Search by product
   *
   *
   *
   * This API fetches transactions for a period based on the below parameters and priority order:
   *
   * 1.    InvoiceNumber
   *
   * 2.    InvoiceDate
   *
   * 3.    FromDate, ToDate
   *
   * 4.    PostingFromDate, PostingToDate (Can be used only when IncludeFees = false)
   *
   * 5.    InvoiceDateFrom, InvoiceDateTo
   *
   * 6.    Period
   *
   *
   *
   * This API considers only one of the above set of parameters at a time. For example, if InvoiceNumber
   * and Period are provided in the input then Period is ignored and transactions associated to the given
   * invoice number are returned.
   *
   *
   *
   * If none of the above parameters are provided then last 7 days transactions will be fetched.
   *
   *
   *
   * This operation can fetch transactions that are old up to 24 (configurable) months. However, the date
   * range between any of the ‘From’ and ‘To’ dates in the above combination cannot be more than 210
   * (configurable) days.
   *
   *
   *
   * @param apikey       This is the API key of the specific environment which needs
   *                                                       to be passed by the client.
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for
   *                                                       requests and responses. This will be played back in the
   *                                                       response from the request.
   * @param body         Priced Transaction Request Body
   * @return Response from the API call
   */
  async pricedTransactions(
    apikey: string,
    requestId: string,
    body?: PriceTransactionRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PricedTransactionResponse>> {
    const req = this.createRequest(
      'POST',
      '/fleetmanagement/v1/transaction/pricedtransactions'
    );
    const mapped = req.prepareArgs({
      apikey: [apikey, string()],
      requestId: [requestId, string()],
      body: [body, optional(priceTransactionRequestSchema)],
    });
    req.header('apikey', mapped.apikey);
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      FleetmanagementV1TransactionPricedtransactions400Error,
      'The server cannot or will not process the request  due to something that is perceived to be a client\r\n error (e.g., malformed request syntax, invalid \r\n request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      FleetmanagementV1TransactionPricedtransactions401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(
      403,
      FleetmanagementV1TransactionPricedtransactions403Error,
      'The server understood the request but refuses to authorize it.'
    );
    req.throwOn(
      404,
      FleetmanagementV1TransactionPricedtransactions404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      FleetmanagementV1TransactionPricedtransactions500Error,
      'The server encountered an unexpected condition the prevented it from fulfilling the request.'
    );
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(pricedTransactionResponseSchema, requestOptions);
  }

  /**
   * This API returns the transaction summary data (i.e. Priced, Billed and Unbilled sales items). It
   * provides a flexible search criteria.
   *
   * The API also supports returning Fee Items. Transactions posted for fee items that are in error are
   * not included in the summary.
   *
   *
   *
   * The endpoint supports the exact same search criteria as the endpoint
   * *transaction/prciedtransactions*.
   *
   *
   *
   * #### Supported operations
   *
   * * Get sales items and fee transactions
   *
   * * Search by invoice status
   *
   * * Search by fixed date period
   *
   * * Search by date range
   *
   * * Search by account
   *
   * * Search by card
   *
   * * Get sales items only
   *
   * * Search by transaction Id or location
   *
   * * Search by transaction posting date
   *
   * * Search by invoice number or date
   *
   * * Search by driver name or vehicle registration number
   *
   * * Search by card group
   *
   * * Search by fuel only transactions
   *
   * * Search by product
   *
   *
   *
   * This API fetches transactions for a period based on the below parameters and priority order:
   *
   * 1.    InvoiceNumber
   *
   * 2.    InvoiceDate
   *
   * 3.    FromDate, ToDate
   *
   * 4.    PostingFromDate, PostingToDate (Can be used only when IncludeFees = false)
   *
   * 5.    InvoiceDateFrom, InvoiceDateTo
   *
   * 6.    Period
   *
   *
   *
   * This API considers only one of the above set of parameters at a time. For example, if InvoiceNumber
   * and Period are provided in the input then Period is ignored and transactions associated to the given
   * invoice number are returned.
   *
   *
   *
   * If none of the above parameters are provided then last 7 days transactions will be fetched.
   *
   * @param apikey       This is the API key of the specific environment which
   *                                                        needs to be passed by the client.
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for
   *                                                        requests and responses. This will be played back in the
   *                                                        response from the request.
   * @param body         PricedSummary RequestBody
   * @return Response from the API call
   */
  async pricedTransactionsSummary(
    apikey: string,
    requestId: string,
    body?: PriceTransSummaryRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PricedTransSummaryResponse>> {
    const req = this.createRequest(
      'POST',
      '/fleetmanagement/v1/transaction/pricedtransactionssummary'
    );
    const mapped = req.prepareArgs({
      apikey: [apikey, string()],
      requestId: [requestId, string()],
      body: [body, optional(priceTransSummaryRequestSchema)],
    });
    req.header('apikey', mapped.apikey);
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      FleetmanagementV1TransactionPricedtransactionssummary400Error,
      'The server cannot or will not process the request  due to something that is perceived to be a client\r\n error (e.g., malformed request syntax, invalid \r\n request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      FleetmanagementV1TransactionPricedtransactionssummary401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(
      403,
      FleetmanagementV1TransactionPricedtransactionssummary403Error,
      'The server understood the request but refuses to authorize it.'
    );
    req.throwOn(
      404,
      FleetmanagementV1TransactionPricedtransactionssummary404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      FleetmanagementV1TransactionPricedtransactionssummary500Error,
      'The server encountered an unexpected condition the prevented it from fulfilling the request.'
    );
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(pricedTransSummaryResponseSchema, requestOptions);
  }

  /**
   * This API allows querying transaction data (i.e. Priced, Billed and Unbilled sales items) for
   * multiple payers. It provides a flexible search criteria and supports paging.
   *
   *
   *
   * Transactions that are posted but not yet priced, billed or that are in error will not be returned by
   * this API. The API also supports returning Fee Items.
   *
   *
   *
   * At least one payer should be provided. Multiple payers must belong to the same payer group.
   *
   *
   *
   * #### Supported operations
   *
   * * Get sales items and fee transactions for multiple payers
   *
   * * Search by invoice status
   *
   * * Search by fixed date period
   *
   * * Search by date range
   *
   * * Get sales items only for multiple payers
   *
   * * Search by transaction location
   *
   * * Search by transaction posting date
   *
   * * Search by invoice number or date
   *
   * * Search by fuel only transactions
   *
   *
   *
   * This API fetches transactions for a period based on the below parameters and priority order:
   *
   * 1.    InvoiceNumber
   *
   * 2.    InvoiceDate
   *
   * 3.    FromDate, ToDate
   *
   * 4.    PostingFromDate, PostingToDate (Can be used only when IncludeFees = false)
   *
   * 5.    InvoiceDateFrom, InvoiceDateTo
   *
   * 6.    Period
   *
   *
   *
   * This API considers only one of the above set of parameters at a time. For example, if InvoiceNumber
   * and Period are provided in the input then Period is ignored and transactions associated to the given
   * invoice number are returned.
   *
   *
   *
   * If none of the above parameters are provided then last 7 days transactions will be fetched.
   *
   * @param apikey       This is the API key of the specific environment which
   *                                                             needs to be passed by the client.
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for
   *                                                             requests and responses. This will be played back in
   *                                                             the response from the request.
   * @param body         MultiPayer RequestBody
   * @return Response from the API call
   */
  async multipricedTransactions(
    apikey: string,
    requestId: string,
    body?: MultiPricedTransactionRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<MultiPricedTransactionResponse>> {
    const req = this.createRequest(
      'POST',
      '/fleetmanagement/v1/transaction/multipayerspricedtransactions'
    );
    const mapped = req.prepareArgs({
      apikey: [apikey, string()],
      requestId: [requestId, string()],
      body: [body, optional(multiPricedTransactionRequestSchema)],
    });
    req.header('apikey', mapped.apikey);
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      FleetmanagementV1TransactionMultipayerspricedtransactions400Error,
      'The server cannot or will not process the request  due to something that is perceived to be a client\r\n error (e.g., malformed request syntax, invalid \r\n request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      FleetmanagementV1TransactionMultipayerspricedtransactions401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(
      403,
      FleetmanagementV1TransactionMultipayerspricedtransactions403Error,
      'The server understood the request but refuses to authorize it.'
    );
    req.throwOn(
      404,
      FleetmanagementV1TransactionMultipayerspricedtransactions404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      FleetmanagementV1TransactionMultipayerspricedtransactions500Error,
      'The server encountered an unexpected condition the prevented it from fulfilling the request.'
    );
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(multiPricedTransactionResponseSchema, requestOptions);
  }

  /**
   * This operation is to provide the expenditure analysis for a card for the past 7 months.
   * The response contains a daily summary of the transactions (billed & unbilled) from 1st of the last 7
   * months for the requested card grouped by card, site-group and product.
   *
   * @param apikey       This is the API key of the specific environment which needs
   *                                                       to be passed by the client.
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for
   *                                                       requests and responses. This will be played back in the
   *                                                       response from the request.
   * @param body         Card Usage Summary RequestBody
   * @return Response from the API call
   */
  async cardUsageSummary(
    apikey: string,
    requestId: string,
    body?: CardUsageSummaryRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CardUsageSummaryResponse>> {
    const req = this.createRequest(
      'POST',
      '/fleetmanagement/v1/transaction/cardusagesummary'
    );
    const mapped = req.prepareArgs({
      apikey: [apikey, string()],
      requestId: [requestId, string()],
      body: [body, optional(cardUsageSummaryRequestSchema)],
    });
    req.header('apikey', mapped.apikey);
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      FleetmanagementV1TransactionCardusagesummary400Error,
      'The server cannot or will not process the request  due to something that is perceived to be a client\r\n error (e.g., malformed request syntax, invalid \r\n request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      FleetmanagementV1TransactionCardusagesummary401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(
      403,
      FleetmanagementV1TransactionCardusagesummary403Error,
      'The server understood the request but refuses to authorize it.'
    );
    req.throwOn(
      404,
      FleetmanagementV1TransactionCardusagesummary404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      FleetmanagementV1TransactionCardusagesummary500Error,
      'The server encountered an unexpected condition the prevented it from fulfilling the request.'
    );
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(cardUsageSummaryResponseSchema, requestOptions);
  }

  /**
   * - This API provides the details of the bonus and/or association bonus rules setup for the given
   * payer and that are active on the current date.
   * - This API also returns the details of the monthly breakup of current period consumption as well as
   * the details of the previously calculated bonus and consumption of the applicable payers.
   *
   *
   *
   * @param apikey       This is the API key of the specific environment which needs
   *                                                       to be passed by the client.
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for
   *                                                       requests and responses. This will be played back in the
   *                                                       response from the request.
   * @param body         VolumeBasedBonus RequestBody
   * @return Response from the API call
   */
  async volumeBasedBonus(
    apikey: string,
    requestId: string,
    body?: VolumeBasedBonusRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<VolumeBasedBonusResponse>> {
    const req = this.createRequest(
      'POST',
      '/fleetmanagement/v1/transaction/volumebasedbonus'
    );
    const mapped = req.prepareArgs({
      apikey: [apikey, string()],
      requestId: [requestId, string()],
      body: [body, optional(volumeBasedBonusRequestSchema)],
    });
    req.header('apikey', mapped.apikey);
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      FleetmanagementV1TransactionVolumebasedbonus400Error,
      'The server cannot or will not process the request  due to something that is perceived to be a client\r\n error (e.g., malformed request syntax, invalid \r\n request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      FleetmanagementV1TransactionVolumebasedbonus401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(
      403,
      FleetmanagementV1TransactionVolumebasedbonus403Error,
      'The server understood the request but refuses to authorize it.'
    );
    req.throwOn(
      404,
      FleetmanagementV1TransactionVolumebasedbonus404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      FleetmanagementV1TransactionVolumebasedbonus500Error,
      'The server encountered an unexpected condition the prevented it from fulfilling the request.'
    );
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(volumeBasedBonusResponseSchema, requestOptions);
  }

  /**
   * - This API will return the details of the in arrear fee rule applied to the payer along with details
   * of locations, products, tiers as applied.
   *
   * - It will also show historical and current volume consumption and related tier applied for the
   * following month.
   *
   *
   *
   * @param apikey       This is the API key of the specific environment which
   *                                                         needs to be passed by the client.
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for
   *                                                         requests and responses. This will be played back in the
   *                                                         response from the request.
   * @param body         VolumeBasedPricing RequestBody
   * @return Response from the API call
   */
  async volumeBasedPricing(
    apikey: string,
    requestId: string,
    body?: VolumeBasedPricingRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<VolumeBasedPricingResponse>> {
    const req = this.createRequest(
      'POST',
      '/fleetmanagement/v1/transaction/volumebasedpricing'
    );
    const mapped = req.prepareArgs({
      apikey: [apikey, string()],
      requestId: [requestId, string()],
      body: [body, optional(volumeBasedPricingRequestSchema)],
    });
    req.header('apikey', mapped.apikey);
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      FleetmanagementV1TransactionVolumebasedpricing400Error,
      'The server cannot or will not process the request  due to something that is perceived to be a client\r\n error (e.g., malformed request syntax, invalid \r\n request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      FleetmanagementV1TransactionVolumebasedpricing401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(
      403,
      FleetmanagementV1TransactionVolumebasedpricing403Error,
      'The server understood the request but refuses to authorize it.'
    );
    req.throwOn(
      404,
      FleetmanagementV1TransactionVolumebasedpricing404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      FleetmanagementV1TransactionVolumebasedpricing500Error,
      'The server encountered an unexpected condition the prevented it from fulfilling the request.'
    );
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(volumeBasedPricingResponseSchema, requestOptions);
  }

  /**
   * This API returns the fee/charges levied from a  customer's account in a billing period or date range.
   * The API returns both billed and unbilled fee items.
   *
   *
   *
   * To get the summary of charges, the endpoint *transaction/feessummary* should be called with the same
   * input criteria.
   *
   *
   *
   * #### Supported operations
   *
   * * Get fees by invoice status
   *
   * * Get fees by date period
   *
   * * Get fees by account
   *
   * * Get fees by card Id or PAN
   *
   * * Get fees by fee type charges
   *
   * * Get fees including cancelled items
   *
   * * Get fees by line item description
   *
   * * Get fees by product
   *
   * @param apikey       This is the API key of the specific environment which needs
   *                                                      to be passed by the client.
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for
   *                                                      requests and responses. This will be played back in the
   *                                                      response from the request.
   * @param body         Transaction Fees RequestBody
   * @return Response from the API call
   */
  async fees(
    apikey: string,
    requestId: string,
    body?: TransactionFeesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TransactionFeesResponse>> {
    const req = this.createRequest(
      'POST',
      '/fleetmanagement/v1/transaction/fees'
    );
    const mapped = req.prepareArgs({
      apikey: [apikey, string()],
      requestId: [requestId, string()],
      body: [body, optional(transactionFeesRequestSchema)],
    });
    req.header('apikey', mapped.apikey);
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      FleetmanagementV1TransactionFees400Error,
      'The server cannot or will not process the request  due to something that is perceived to be a client\r\n error (e.g., malformed request syntax, invalid \r\n request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      FleetmanagementV1TransactionFees401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(
      403,
      FleetmanagementV1TransactionFees403Error,
      'The server understood the request but refuses to authorize it.'
    );
    req.throwOn(
      404,
      FleetmanagementV1TransactionFees404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      FleetmanagementV1TransactionFees500Error,
      'The server encountered an unexpected condition the prevented it from fulfilling the request.'
    );
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(transactionFeesResponseSchema, requestOptions);
  }

  /**
   * This API returns the summary data of the fee/charges levied from a customer's account in a billing
   * period or date range. The API returns both billed and unbilled fee items.
   *
   *
   *
   * The endpoint supports the exact same search criteria as the endpoint *transaction/feessummary*.
   *
   *
   *
   * #### Supported operations
   *
   * * Get fees by invoice status
   *
   * * Get fees by date period
   *
   * * Get fees by account
   *
   * * Get fees by card Id or PAN
   *
   * * Get fees by fee type charges
   *
   * * Get fees including cancelled items
   *
   * * Get fees by line item description
   *
   * * Get fees by product
   *
   * @param apikey       This is the API key of the specific environment which needs
   *                                                      to be passed by the client.
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for
   *                                                      requests and responses. This will be played back in the
   *                                                      response from the request.
   * @param body         FeeSummary RequestBody
   * @return Response from the API call
   */
  async feeSummaryResponse(
    apikey: string,
    requestId: string,
    body?: TransactionFeesRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FeeSummaryResponse>> {
    const req = this.createRequest(
      'POST',
      '/fleetmanagement/v1/transaction/feessummary'
    );
    const mapped = req.prepareArgs({
      apikey: [apikey, string()],
      requestId: [requestId, string()],
      body: [body, optional(transactionFeesRequestSchema)],
    });
    req.header('apikey', mapped.apikey);
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      FleetmanagementV1TransactionFeessummary400Error,
      'The server cannot or will not process the request  due to something that is perceived to be a client\r\n error (e.g., malformed request syntax, invalid \r\n request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      FleetmanagementV1TransactionFeessummary401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(
      403,
      FleetmanagementV1TransactionFeessummary403Error,
      'The server understood the request but refuses to authorize it.'
    );
    req.throwOn(
      404,
      FleetmanagementV1TransactionFeessummary404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      FleetmanagementV1TransactionFeessummary500Error,
      'The server encountered an unexpected condition the prevented it from fulfilling the request.'
    );
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(feeSummaryResponseSchema, requestOptions);
  }

  /**
   * - This API returns the customer an overview of how many transactions, how much fuel volume used over
   * a given period and the total volume used by a card
   *
   * - This operation response will contains card & transaction details for given period aggregated by
   * payer, account, cardGroup, PAN, DriverName and VRN
   *
   *
   *
   * @param apikey       This is the API key of the specific environment which needs
   *                                                      to be passed by the client.
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for
   *                                                      requests and responses. This will be played back in the
   *                                                      response from the request.
   * @param body         FuelConsumption RequestBody
   * @return Response from the API call
   */
  async fuelConsumption(
    apikey: string,
    requestId: string,
    body?: FuelConsumptionRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FuelConsumptionResponse>> {
    const req = this.createRequest(
      'POST',
      '/fleetmanagement/v1/transaction/fuelconsumption'
    );
    const mapped = req.prepareArgs({
      apikey: [apikey, string()],
      requestId: [requestId, string()],
      body: [body, optional(fuelConsumptionRequestSchema)],
    });
    req.header('apikey', mapped.apikey);
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      FleetmanagementV1TransactionFuelconsumption400Error,
      'The server cannot or will not process the request  due to something that is perceived to be a client\r\n error (e.g., malformed request syntax, invalid \r\n request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      FleetmanagementV1TransactionFuelconsumption401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(
      403,
      FleetmanagementV1TransactionFuelconsumption403Error,
      'The server understood the request but refuses to authorize it.'
    );
    req.throwOn(
      404,
      FleetmanagementV1TransactionFuelconsumption404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      FleetmanagementV1TransactionFuelconsumption500Error,
      'The server encountered an unexpected condition the prevented it from fulfilling the request.'
    );
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(fuelConsumptionResponseSchema, requestOptions);
  }

  /**
   * - This API allows the users to update the odometer readings on the sales items (transaction data)
   *
   * - This is an asynchronous operation. If opted, the user will be notified on completion of processing.
   *
   * @param apikey       This is the API key of the specific environment which needs
   *                                                     to be passed by the client.
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for requests
   *                                                     and responses. This will be played back in the response from
   *                                                     the request.
   * @param body         updateOdometer RequestBody
   * @return Response from the API call
   */
  async updateOdometer(
    apikey: string,
    requestId: string,
    body?: UpdateOdometerRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UpdateOdometerResponse>> {
    const req = this.createRequest(
      'POST',
      '/fleetmanagement/v1/transaction/updateodometer'
    );
    const mapped = req.prepareArgs({
      apikey: [apikey, string()],
      requestId: [requestId, string()],
      body: [body, optional(updateOdometerRequestSchema)],
    });
    req.header('apikey', mapped.apikey);
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      FleetmanagementV1TransactionUpdateodometer400Error,
      'The server cannot or will not process the request  due to something that is perceived to be a client\r\n error (e.g., malformed request syntax, invalid \r\n request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      FleetmanagementV1TransactionUpdateodometer401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(
      403,
      FleetmanagementV1TransactionUpdateodometer403Error,
      'The server understood the request but refuses to authorize it.'
    );
    req.throwOn(
      404,
      FleetmanagementV1TransactionUpdateodometer404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      FleetmanagementV1TransactionUpdateodometer500Error,
      'The server encountered an unexpected condition the prevented it from fulfilling the request.'
    );
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(updateOdometerResponseSchema, requestOptions);
  }

  /**
   * - This API provides the details of the Cards or Transaction related exceptions based on the given
   * conditions for the Requested period.
   * - This API will return the Transactions related exceptions when the OutputType input parameter is
   * passed as ‘Transaction’ else will return the Cards related exceptions.
   *
   *
   *
   * @param apikey       This is the API key of the specific environment which
   *                                                            needs to be passed by the client.
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for
   *                                                            requests and responses. This will be played back in the
   *                                                            response from the request.
   * @param body         Transaction Exceptions RequestBody
   * @return Response from the API call
   */
  async transactionExceptions(
    apikey: string,
    requestId: string,
    body?: TransactionExceptionsRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TransactionExceptionsResponse>> {
    const req = this.createRequest(
      'POST',
      '/fleetmanagement/v1/transaction/exceptions'
    );
    const mapped = req.prepareArgs({
      apikey: [apikey, string()],
      requestId: [requestId, string()],
      body: [body, optional(transactionExceptionsRequestSchema)],
    });
    req.header('apikey', mapped.apikey);
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      FleetmanagementV1TransactionExceptions400Error,
      'The server cannot or will not process the request  due to something that is perceived to be a client\r\n error (e.g., malformed request syntax, invalid \r\n request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      FleetmanagementV1TransactionExceptions401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(
      403,
      FleetmanagementV1TransactionExceptions403Error,
      'The server understood the request but refuses to authorize it.'
    );
    req.throwOn(
      404,
      FleetmanagementV1TransactionExceptions404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      FleetmanagementV1TransactionExceptions500Error,
      'The server encountered an unexpected condition the prevented it from fulfilling the request.'
    );
    req.authenticate([{ basicAuth: true }]);
    return req.callAsJson(transactionExceptionsResponseSchema, requestOptions);
  }

  /**
   * This endpoint allows querying last 48 hours of transaction data of Shell Card (i.e. Priced, Billed,
   * Unbilled etc. sales items). It provides a flexible search criteria and supports pagination. E.g., if
   * the request is made at 08:30 AM on 18 Aug 2022 then transactions until 16 Aug 2022 08:30 AM
   * (including) can be retrieved.
   *
   *
   * #### Supported operations
   *
   * * Search by Date and Time range (within the last 48 hours only)
   *
   * * Search by Payer and/or Account number
   *
   * * Search by Card
   *
   * * Search by Purchased Country
   *
   * * Search by Transaction posting date
   *
   * * Search by Driver Name or Vehicle registration number
   *
   * * Search by Fuel only transactions
   *
   * * Search by Product and/or Product group
   *
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for
   *                                                        requests and responses. This will be played back in the
   *                                                        response from the request.
   * @param body         New Recent Transaction RequestBody
   * @return Response from the API call
   */
  async recentTransactionsNew(
    requestId: string,
    body?: RecentTransactionRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<RecentTransactionsResponse>> {
    const req = this.createRequest('POST', '/transaction-data/v1/recent');
    const mapped = req.prepareArgs({
      requestId: [requestId, string()],
      body: [body, optional(recentTransactionRequestSchema)],
    });
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      TransactionDataV1Recent400Error,
      'The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      TransactionDataV1Recent401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(403, TransactionDataV1Recent403Error, 'Forbidden');
    req.throwOn(
      404,
      TransactionDataV1Recent404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      TransactionDataV1Recent500Error,
      'The server encountered an unexpected condition that  prevented it from fulfilling the request.'
    );
    req.authenticate([{ bearerToken: true }]);
    return req.callAsJson(recentTransactionsResponseSchema, requestOptions);
  }

  /**
   * This API allows querying transaction data (i.e. Priced, Billed and Unbilled sales items). It
   * provides a flexible search criteria and supports paging.
   *
   * The version 2 is an enhancement to the version 1 where EV transactions and their details are added
   * in the response.
   *
   *
   *
   * Transactions that are posted but not yet priced, billed or that are in error will not be returned by
   * this API. The API also supports returning Fee Items.
   *
   *
   *
   * #### Supported operations
   *
   * * Get sales items and fee transactions
   *
   * * Search by invoice status
   *
   * * Search by fixed date period
   *
   * * Search by date range
   *
   * * Search by account
   *
   * * Search by card
   *
   * * Get sales items only
   *
   * * Search by transaction Id or location
   *
   * * Search by transaction posting date
   *
   * * Search by invoice number or date
   *
   * * Search by driver name or vehicle registration number
   *
   * * Search by card group
   *
   * * Search by fuel only transactions
   *
   * * Search by product
   *
   * * EV transaction details - Below are EV specific parameters
   *
   * * EVOperator
   *
   * * EVSerialId
   *
   * * EVChargePointSerial
   *
   * * EVChargePointConnectorType
   *
   * * EVChargePointConnectorTypeDescription
   *
   * * EVChargeDuration
   *
   * * EVChargeStartDate
   *
   * * EVChargeStartTime
   *
   * * EVChargeEndDate
   *
   * * EVChargeEndTime
   *
   *
   * @param requestId    Mandatory UUID (according to RFC 4122 standards) for
   *                                                          requests and responses. This will be played back in the
   *                                                          response from the request.
   * @param body         Priced TransactionV2 RequestBody
   * @return Response from the API call
   */
  async pricedTransactionsV2(
    requestId: string,
    body?: PricedTransactionRequestV2,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PricedTransactionResponseV2>> {
    const req = this.createRequest('POST', '/transaction-data/v1/priced');
    const mapped = req.prepareArgs({
      requestId: [requestId, string()],
      body: [body, optional(pricedTransactionRequestV2Schema)],
    });
    req.header('RequestId', mapped.requestId);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      TransactionDataV1Priced400Error,
      'The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).'
    );
    req.throwOn(
      401,
      TransactionDataV1Priced401Error,
      'The request has not been applied because it lacks valid  authentication credentials for the target resource.'
    );
    req.throwOn(403, TransactionDataV1Priced403Error, 'Forbidden');
    req.throwOn(
      404,
      TransactionDataV1Priced404Error,
      'The origin server did not find a current representation  for the target resource or is not willing to disclose  that one exists.'
    );
    req.throwOn(
      500,
      TransactionDataV1Priced500Error,
      'The server encountered an unexpected condition that  prevented it from fulfilling the request.'
    );
    req.authenticate([{ bearerToken: true }]);
    return req.callAsJson(pricedTransactionResponseV2Schema, requestOptions);
  }
}
