/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface Accounts {
  /**
   * Account Id of the customer.
   * Optional, if AccountNumber is passed, else mandatory.
   */
  accountId?: number | null;
  /**
   * Account Number of the customer.
   * Optional, if AccountId is passed, else mandatory.
   */
  accountNumber?: string | null;
}

export const accountsSchema: Schema<Accounts> = object({
  accountId: ['AccountId', optional(nullable(number()))],
  accountNumber: ['AccountNumber', optional(nullable(string()))],
});
