/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface AssociatedAccount {
  /** Account identifier  of the Associated Account associated with the Payer. */
  associatedAccountId?: number | null;
  /** Account number of the Associated Account associated with the Payer. */
  associatedAccountNumber?: string | null;
  /** Account associated with the Payer. */
  associatedAccountShortName?: string | null;
  /** Full name of the Associated Account associated with the Payer. */
  associatedAccountFullName?: string | null;
}

export const associatedAccountSchema: Schema<AssociatedAccount> = object({
  associatedAccountId: ['AssociatedAccountId', optional(nullable(number()))],
  associatedAccountNumber: [
    'AssociatedAccountNumber',
    optional(nullable(string())),
  ],
  associatedAccountShortName: [
    'AssociatedAccountShortName',
    optional(nullable(string())),
  ],
  associatedAccountFullName: [
    'AssociatedAccountFullName',
    optional(nullable(string())),
  ],
});
