/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Accounts, accountsSchema } from './accounts';

export interface AuditRequest {
  /**
   * Status of requests to be fetched.
   * •    Success
   * •    Failed
   * •    InProgress
   * •    Submitted
   * •    Rejected
   * •    PendingApproval
   * •    All
   * •    MailedToCSC
   * Optional
   * If not passed “All” will be considered as the default value.
   */
  status?: string;
  /**
   * Payer Number of the selected payer.
   * Optional if PayerId is passed else Mandatory
   */
  payerNumber?: string | null;
  /**
   * Payer Id  of the selected payer.
   * Optional if PayerNumber is passed else Mandatory
   * Example: 123456
   */
  payerId?: number | null;
  accountNumber?: string | null;
  /**
   * Collecting Company Code (Shell Code) of the selected payer.
   * Mandatory for serviced OUs such as Romania, Latvia, Lithuania, Estonia, Ukraine etc. It is optional for other countries if ColCoID is provided.
   * Example:
   * 86 for Philippines
   * 5 for UK
   */
  colCoCode?: number | null;
  /**
   * Collecting Company Id  of the selected payer.
   * Optional if ColCoCode is passed else Mandatory.
   * Example:
   * 1 for Philippines
   * 5 for UK
   */
  colCoId?: number | null;
  accounts?: Accounts;
  /**
   * Page Size – Number of records to show on a page
   * Optional
   * Default value 50
   */
  pageSize?: number;
  /**
   * To search for requests submitted until this date.
   * Optional
   * Format: yyyyMMdd
   * Example: 20200130
   * If ToDate is not provided and FromDate is provided, then ToDate will be considered as current date or 30 days from FromDate, whichever is earlier. However, when both FromDate and ToDate is not provided then last 30 days will be considered for filtering.
   */
  requestedOperation?: string[];
  /**
   * Allowed Sorting Options:
   * 1.    SubmittedDateDescending
   * 2.    SubmittedDateAscending
   * 3.    AccountNumberAscending
   * 4.    AccountNumberDescending
   * Optional: Default value is 1
   * Example value to be passed: 1,3
   */
  sortOrder?: string | null;
  /**
   * Search text used as criteria to filter the requests.
   * Optional
   * Minimum length is 4 characters (configurable). Else, an error (0007) will be returned. When valid text is provided, MS will return all the records that contains the Search Text within any of the look up fields
   */
  searchText?: string | null;
  /**
   * Page Number (as shown to the users)
   * Optional
   * Default value 1
   */
  currentPage?: number | null;
  /**
   * To search for requests submitted from this date.
   * Optional
   * Maximum of X days duration allowed per search. The X value is configurable and initially set to 180 days.
   * Format: yyyyMMdd
   * Example: 20200101
   * If FromDate is not provided and ToDate is provided, then FromDate will be considered as 30 days less than ToDate. However, when both FromDate and ToDate is not provided then last 30 days will be considered for filtering.
   */
  fromDate?: string | null;
  /**
   * To search for requests submitted until this date.
   * Optional
   * Format: yyyyMMdd
   * Example: 20200130
   * If ToDate is not provided and FromDate is provided, then ToDate will be considered as current date or 30 days from FromDate, whichever is earlier. However, when both FromDate and ToDate is not provided then last 30 days will be considered for filtering.
   */
  toDate?: string | null;
}

export const auditRequestSchema: Schema<AuditRequest> = object({
  status: ['Status', optional(string())],
  payerNumber: ['PayerNumber', optional(nullable(string()))],
  payerId: ['PayerId', optional(nullable(number()))],
  accountNumber: ['AccountNumber', optional(nullable(string()))],
  colCoCode: ['ColCoCode', optional(nullable(number()))],
  colCoId: ['ColCoId', optional(nullable(number()))],
  accounts: ['Accounts', optional(lazy(() => accountsSchema))],
  pageSize: ['PageSize', optional(number())],
  requestedOperation: ['RequestedOperation', optional(array(string()))],
  sortOrder: ['SortOrder', optional(nullable(string()))],
  searchText: ['SearchText', optional(nullable(string()))],
  currentPage: ['CurrentPage', optional(nullable(number()))],
  fromDate: ['FromDate', optional(nullable(string()))],
  toDate: ['ToDate', optional(nullable(string()))],
});
