/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  AuditResponseAuditsItems,
  auditResponseAuditsItemsSchema,
} from './auditResponseAuditsItems.js';

export interface AuditArrayElements {
  audits?: AuditResponseAuditsItems[];
}

export const auditArrayElementsSchema: Schema<AuditArrayElements> = lazy(() =>
  object({
    audits: ['Audits', optional(array(auditResponseAuditsItemsSchema))],
  })
);
