/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema';

export interface CardTypeResponseError {
  code?: string;
  description?: string;
}

export const cardTypeResponseErrorSchema: Schema<CardTypeResponseError> = object(
  {
    code: ['Code', optional(string())],
    description: ['Description', optional(string())],
  }
);
