/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  CardUsageSummaryRequest,
  cardUsageSummaryRequestSchema,
} from './cardUsageSummaryRequest.js';

export interface CardUsageSummaryReq {
  filters?: CardUsageSummaryRequest;
}

export const cardUsageSummaryReqSchema: Schema<CardUsageSummaryReq> = lazy(() =>
  object({ filters: ['Filters', optional(cardUsageSummaryRequestSchema)] })
);
