/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';

export interface ColCoAccess {
  /** Collecting company ID. */
  colCoId?: number | null;
  /** Collecting company code. */
  colCoCode?: number | null;
  /** Collecting company’s Country name. ex: United Kingdom */
  colCoCountryName?: string | null;
  /**
   * Issuing Country Number.
   *  ex: 032 - Czech Republic
   */
  issuingCountryNumber?: string | null;
}

export const colCoAccessSchema: Schema<ColCoAccess> = object({
  colCoId: ['ColCoId', optional(nullable(number()))],
  colCoCode: ['ColCoCode', optional(nullable(number()))],
  colCoCountryName: ['ColCoCountryName', optional(nullable(string()))],
  issuingCountryNumber: ['IssuingCountryNumber', optional(nullable(string()))],
});
