/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface CurrentVolume {
  /** Bonus or association bonus configuration identifier that is associated to the payer */
  feeRuleId?: number | null;
  /** Bonus or association bonus configuration description that is associated to the payer. */
  feeRuleDescription?: string | null;
  /** Consumption(Volume) of the month. */
  month?: number | null;
  /** Consumption (Volume) of the year. */
  year?: string | null;
  /** Total volume consumption for the month/year above. */
  totalVolume?: number | null;
}

export const currentVolumeSchema: Schema<CurrentVolume> = object({
  feeRuleId: ['FeeRuleId', optional(nullable(number()))],
  feeRuleDescription: ['FeeRuleDescription', optional(nullable(string()))],
  month: ['Month', optional(nullable(number()))],
  year: ['Year', optional(nullable(string()))],
  totalVolume: ['TotalVolume', optional(nullable(number()))],
});
