/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  CustomerDetailResponse,
  customerDetailResponseSchema,
} from './customerDetailResponse.js';

export interface CustomerRes {
  /** Unique identifier for the request. This will be played back in the response from the request. */
  requestId?: string;
  /** Status of the request */
  status?: string;
  data?: CustomerDetailResponse[];
}

export const customerResSchema: Schema<CustomerRes> = lazy(() =>
  object({
    requestId: ['RequestId', optional(string())],
    status: ['Status', optional(string())],
    data: ['Data', optional(array(customerDetailResponseSchema))],
  })
);
