/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { PriceList, priceListSchema } from './priceList.js';

export interface CustomerPriceListResponse {
  priceList?: PriceList[];
}

export const customerPriceListResponseSchema: Schema<CustomerPriceListResponse> = lazy(
  () => object({ priceList: ['PriceList', optional(array(priceListSchema))] })
);
