/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface CustomerPriceListRequest {
  colCoId?: number | null;
  colCoCode?: number | null;
  /**
   * Payer Id of the selected payer.
   * Optional if PayerNumber is passed else Mandatory
   */
  payerId?: number | null;
  /**
   * Payer Number of the selected payer.
   * Optional if PayerId is passed else Mandatory
   */
  payerNumber?: string | null;
  /**
   * Account Id of the customer.
   * Optional
   */
  accountId?: number | null;
  /**
   * Account Number of the customer.
   * Optional
   */
  accountNumber?: string | null;
  /** Whether customer specific price lists and customer specific discount values set on pump prices are to be returned or not. */
  customerSpecificList?: number | null;
  /**
   * Specifies the type of price lists to be included in the response.
   * Optional – default value is zero.
   * Allowed values:
   * 0 – All
   * 1 – National Only
   * 2 – International Only
   */
  priceListType?: number | null;
  /**
   * Delivering Company ID
   * Optional.
   */
  delCoId?: number | null;
  /**
   * Start date to fetch the price lists, discount values on pump prices and VAT rates.
   * Mandatory
   * Format: yyyyMMdd
   */
  fromDate: string | null;
  /**
   * End date to fetch the price lists, discount values on pump prices and VAT rates.
   * Mandatory and greater than or equal to FromDate.
   * Maximum of 30 (configurable) day’s duration is allowed between ‘From’ and ‘To’ dates.
   * Format: yyyyMMdd
   */
  toDate: string | null;
  /**
   * True / False.
   * A flag to request the discount information set on pump prices for the customer to be included in the response.
   * Optional
   * Default value: False
   */
  includePumpPriceDiscounts?: boolean | null;
}

export const customerPriceListRequestSchema: Schema<CustomerPriceListRequest> = object(
  {
    colCoId: ['ColCoId', optional(nullable(number()))],
    colCoCode: ['ColCoCode', optional(nullable(number()))],
    payerId: ['PayerId', optional(nullable(number()))],
    payerNumber: ['PayerNumber', optional(nullable(string()))],
    accountId: ['AccountId', optional(nullable(number()))],
    accountNumber: ['AccountNumber', optional(nullable(string()))],
    customerSpecificList: [
      'CustomerSpecificList',
      optional(nullable(number())),
    ],
    priceListType: ['PriceListType', optional(nullable(number()))],
    delCoId: ['DelCoId', optional(nullable(number()))],
    fromDate: ['FromDate', nullable(string())],
    toDate: ['ToDate', nullable(string())],
    includePumpPriceDiscounts: [
      'IncludePumpPriceDiscounts',
      optional(nullable(boolean())),
    ],
  }
);
