/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  CustomerDetailRequest,
  customerDetailRequestSchema,
} from './customerDetailRequest.js';

export interface CustomerReq {
  filters?: CustomerDetailRequest;
}

export const customerReqSchema: Schema<CustomerReq> = lazy(() =>
  object({ filters: ['Filters', optional(customerDetailRequestSchema)] })
);
