/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  CustomerPriceListRequest,
  customerPriceListRequestSchema,
} from './customerPriceListRequest.js';

export interface CustomerPriceListReq {
  filters?: CustomerPriceListRequest;
}

export const customerPriceListReqSchema: Schema<CustomerPriceListReq> = lazy(
  () =>
    object({ filters: ['Filters', optional(customerPriceListRequestSchema)] })
);
