/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ErrorStatus, errorStatusSchema } from './errorStatus';
import { PriceList, priceListSchema } from './priceList';

export interface CustomerPriceListResponse {
  /** UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the request. */
  requestId?: string;
  priceList?: PriceList[];
  error?: ErrorStatus;
}

export const customerPriceListResponseSchema: Schema<CustomerPriceListResponse> = object(
  {
    requestId: ['RequestId', optional(string())],
    priceList: ['PriceList', optional(array(lazy(() => priceListSchema)))],
    error: ['Error', optional(lazy(() => errorStatusSchema))],
  }
);
