/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { Fault, faultSchema } from './fault';

/** Error response */
export interface DefaultError {
  fault?: Fault;
}

export const defaultErrorSchema: Schema<DefaultError> = object({
  fault: ['fault', optional(lazy(() => faultSchema))],
});
