/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema';
import { EIDDownloadReq, eIDDownloadReqSchema } from './eIDDownloadReq';

export interface EIDDownloadRequest {
  filters?: EIDDownloadReq;
}

export const eIDDownloadRequestSchema: Schema<EIDDownloadRequest> = object({
  filters: ['Filters', optional(lazy(() => eIDDownloadReqSchema))],
});
