/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ErrorStatus, errorStatusSchema } from './errorStatus';
import {
  FeeItemSummaryAllOf0,
  feeItemSummaryAllOf0Schema,
} from './feeItemSummaryAllOf0';

export interface FeeSummaryResponse {
  feeItemsSummary?: FeeItemSummaryAllOf0[];
  /** A unique request id in GUID format. The value is written to the Shell API Platform audit log for end to end traceability of a request. If a value is not provided by an API client, then a GUID is automatically populated by the Shell API Platform and returned in the API response. */
  requestId?: string;
  error?: ErrorStatus;
}

export const feeSummaryResponseSchema: Schema<FeeSummaryResponse> = object({
  feeItemsSummary: [
    'FeeItemsSummary',
    optional(array(lazy(() => feeItemSummaryAllOf0Schema))),
  ],
  requestId: ['RequestId', optional(string())],
  error: ['Error', optional(lazy(() => errorStatusSchema))],
});
