/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface FeesFeeRuleTiers {
  tierMin?: number | null;
  tierMax?: number | null;
  dateEffective?: string | null;
  dateTerminated?: string | null;
  tierValue?: number | null;
  feeRuleBasisID?: number | null;
  feeRuleBasisDescription?: string | null;
}

export const feesFeeRuleTiersSchema: Schema<FeesFeeRuleTiers> = object({
  tierMin: ['TierMin', optional(nullable(number()))],
  tierMax: ['TierMax', optional(nullable(number()))],
  dateEffective: ['DateEffective', optional(nullable(string()))],
  dateTerminated: ['DateTerminated', optional(nullable(string()))],
  tierValue: ['TierValue', optional(nullable(number()))],
  feeRuleBasisID: ['FeeRuleBasisID', optional(nullable(number()))],
  feeRuleBasisDescription: [
    'FeeRuleBasisDescription',
    optional(nullable(string())),
  ],
});
