/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface FuelConsumptionData {
  /** Account Name */
  accountName?: string | null;
  /** Account Number */
  accountNumber?: string | null;
  /** Payment customer Name */
  payerName?: string | null;
  /** Payment customer number */
  payerNumber?: string | null;
  /** Card PAN */
  cardNumber?: string | null;
  /** Card group ID */
  cardGroupId?: number | null;
  /** Card group name */
  cardGroupName?: string | null;
  /** Driver name */
  driverName?: string | null;
  /** Vehicle registration number */
  licenseNumber?: string | null;
  /** First transaction odometer reading */
  initialOdometer?: number | null;
  /** Last transaction odometer reading */
  lastOdometer?: number | null;
  /** Distance in  KM or Miles based on Customer and Colco Settings */
  distance?: number | null;
  /** Total Fuel Consumption. */
  fuelConsumption?: number | null;
  /** Net Fuel Amount */
  fuelNetAmount?: number | null;
  /** Total Discount */
  discount?: number | null;
  /** Fuel Tax Amount */
  fuelTax?: number | null;
  /** Total Fuel Volume in Litres */
  fuelVolume?: number | null;
  /** Gross Nonfuel Amount */
  grossNonFuelExpenses?: number | null;
  /** Total Co2 produced */
  cO2Produced?: number | null;
  /** Total Transaction Count */
  transactionCount?: number | null;
}

export const fuelConsumptionDataSchema: Schema<FuelConsumptionData> = object({
  accountName: ['AccountName', optional(nullable(string()))],
  accountNumber: ['AccountNumber', optional(nullable(string()))],
  payerName: ['PayerName', optional(nullable(string()))],
  payerNumber: ['PayerNumber', optional(nullable(string()))],
  cardNumber: ['CardNumber', optional(nullable(string()))],
  cardGroupId: ['CardGroupId', optional(nullable(number()))],
  cardGroupName: ['CardGroupName', optional(nullable(string()))],
  driverName: ['DriverName', optional(nullable(string()))],
  licenseNumber: ['LicenseNumber', optional(nullable(string()))],
  initialOdometer: ['InitialOdometer', optional(nullable(number()))],
  lastOdometer: ['LastOdometer', optional(nullable(number()))],
  distance: ['Distance', optional(nullable(number()))],
  fuelConsumption: ['FuelConsumption', optional(nullable(number()))],
  fuelNetAmount: ['FuelNetAmount', optional(nullable(number()))],
  discount: ['Discount', optional(nullable(number()))],
  fuelTax: ['FuelTax', optional(nullable(number()))],
  fuelVolume: ['FuelVolume', optional(nullable(number()))],
  grossNonFuelExpenses: ['GrossNonFuelExpenses', optional(nullable(number()))],
  cO2Produced: ['CO2Produced', optional(nullable(number()))],
  transactionCount: ['TransactionCount', optional(nullable(number()))],
});
