/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface FuelConsumptionCard {
  /**
   * Card Id
   * Optional, when PAN is provided else mandatory.
   */
  cardId?: number;
  /**
   * Full Card PAN
   * Optional, when CardId is provided else mandatory.
   */
  pAN?: string;
  /**
   * Card Expiry Date
   * Format: yyyyMMdd
   */
  expiryDate?: string;
}

export const fuelConsumptionCardSchema: Schema<FuelConsumptionCard> = object({
  cardId: ['CardId', optional(number())],
  pAN: ['PAN', optional(string())],
  expiryDate: ['ExpiryDate', optional(string())],
});
