/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  FuelConsumptionRequest,
  fuelConsumptionRequestSchema,
} from './fuelConsumptionRequest.js';

export interface FuelConsumptionReq {
  filters?: FuelConsumptionRequest;
}

export const fuelConsumptionReqSchema: Schema<FuelConsumptionReq> = lazy(() =>
  object({ filters: ['Filters', optional(fuelConsumptionRequestSchema)] })
);
