/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema';
import { ErrorStatus, errorStatusSchema } from './errorStatus';
import {
  FuelConsumptionData,
  fuelConsumptionDataSchema,
} from './fuelConsumptionData';

export interface FuelConsumptionResponse {
  fuelConsumption?: FuelConsumptionData[];
  error?: ErrorStatus;
  /** API Request Id */
  requestId?: string;
}

export const fuelConsumptionResponseSchema: Schema<FuelConsumptionResponse> = object(
  {
    fuelConsumption: [
      'FuelConsumption',
      optional(array(lazy(() => fuelConsumptionDataSchema))),
    ],
    error: ['Error', optional(lazy(() => errorStatusSchema))],
    requestId: ['RequestId', optional(string())],
  }
);
