/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  InvoiceSummaryDetails,
  invoiceSummaryDetailsSchema,
} from './invoiceSummaryDetails.js';

export interface InvoiceSummaryResponse {
  /** API Request Id */
  requestId?: string;
  /** Indicates overall status of the request. Allowed values: SUCCES, FAILED */
  status?: string;
  data?: InvoiceSummaryDetails[];
}

export const invoiceSummaryResponseSchema: Schema<InvoiceSummaryResponse> = lazy(
  () =>
    object({
      requestId: ['RequestId', optional(string())],
      status: ['Status', optional(string())],
      data: ['Data', optional(array(invoiceSummaryDetailsSchema))],
    })
);
