/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  InvoiceDatesData,
  invoiceDatesDataSchema,
} from './invoiceDatesData.js';

export interface InvoiceDatesResponseData {
  /** Unique request identifier passed from end user. This identifier helps in tracing a transaction */
  requestId?: string;
  /** Indicates overall status of the request. Allowed values: SUCCES, FAILED */
  status?: string;
  data?: InvoiceDatesData[];
}

export const invoiceDatesResponseDataSchema: Schema<InvoiceDatesResponseData> = lazy(
  () =>
    object({
      requestId: ['RequestId', optional(string())],
      status: ['Status', optional(string())],
      data: ['Data', optional(array(invoiceDatesDataSchema))],
    })
);
