/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  InvoiceDownloadReq,
  invoiceDownloadReqSchema,
} from './invoiceDownloadReq.js';

export interface InvoiceDownloadRequest {
  filters?: InvoiceDownloadReq;
}

export const invoiceDownloadRequestSchema: Schema<InvoiceDownloadRequest> = lazy(
  () => object({ filters: ['Filters', optional(invoiceDownloadReqSchema)] })
);
