/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, number, object, optional, Schema } from '../schema';
import {
  InvoiceSearchRequestFilters,
  invoiceSearchRequestFiltersSchema,
} from './invoiceSearchRequestFilters';

export interface InvoiceSearchRequest {
  filters?: InvoiceSearchRequestFilters;
  pageSize?: number;
  page?: number;
  /**
   * Sort option –
   * 1.	InvoiceDate ASC
   * 2.	InvoiceDate DESC
   * 3.	NetAmountCustomerCurrency ASC
   * 4.	NetAmountCustomerCurrency DESC
   * Optional
   * Note:
   * This option uses a column name with a combination of “ASC or DESC” for sorting.
   * If only the column name is provided, it is sorted by ascending.
   * Example values to be passed:
   * [“InvoiceDate”, “NetAmountCustomerCurrency DESC”]
   */
  sortBy?: number[];
}

export const invoiceSearchRequestSchema: Schema<InvoiceSearchRequest> = object({
  filters: ['Filters', optional(lazy(() => invoiceSearchRequestFiltersSchema))],
  pageSize: ['PageSize', optional(number())],
  page: ['Page', optional(number())],
  sortBy: ['SortBy', optional(array(number()))],
});
