/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, number, object, optional, Schema, string } from '../schema';

export interface InvoiceSummaryDetails {
  /** Total number of invoices matching with the given search criteria. */
  totalInvoices?: number | null;
  /** Total gross amount in customer currency combined from all the invoices matching with the given search criteria. */
  totalGrossAmountCustomerCurrency?: number | null;
  /** Total net amount in customer currency combined from all the invoices matching with the given search criteria. */
  totalNetAmountCustomerCurrency?: number | null;
  /** Total VAT amount in customer currency combined from all the invoices matching with the given search criteria. */
  totalVATAmountCustomerCurrency?: number | null;
  /**
   * Customer currency ISO code.
   * Example: EUR
   */
  customerCurrencyCode?: string | null;
  /**
   * Customer currency code.
   * Example: €
   */
  customerCurrencySymbol?: string | null;
}

export const invoiceSummaryDetailsSchema: Schema<InvoiceSummaryDetails> = object(
  {
    totalInvoices: ['TotalInvoices', optional(nullable(number()))],
    totalGrossAmountCustomerCurrency: [
      'TotalGrossAmountCustomerCurrency',
      optional(nullable(number())),
    ],
    totalNetAmountCustomerCurrency: [
      'TotalNetAmountCustomerCurrency',
      optional(nullable(number())),
    ],
    totalVATAmountCustomerCurrency: [
      'TotalVATAmountCustomerCurrency',
      optional(nullable(number())),
    ],
    customerCurrencyCode: [
      'CustomerCurrencyCode',
      optional(nullable(string())),
    ],
    customerCurrencySymbol: [
      'CustomerCurrencySymbol',
      optional(nullable(string())),
    ],
  }
);
