/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { nullable, object, optional, Schema, string } from '../schema';

export interface Location {
  /** Latitude for the Site Geographic Location */
  lat?: string | null;
  /** Longitude for the Site Geographic Location */
  lng?: string | null;
}

export const locationSchema: Schema<Location> = object({
  lat: ['Lat', optional(nullable(string()))],
  lng: ['Lng', optional(nullable(string()))],
});
