/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { AccountAccess, accountAccessSchema } from './accountAccess';
import { ColCoAccess, colCoAccessSchema } from './colCoAccess';
import { EIDAccess, eIDAccessSchema } from './eIDAccess';
import { ErrorStatus, errorStatusSchema } from './errorStatus';
import { PayerAccess, payerAccessSchema } from './payerAccess';
import { Role, roleSchema } from './role';

export interface LoggedInUserResponse {
  /** Logged in User Identifier */
  userName?: string | null;
  /** Name of the logged in user. */
  displayName?: string | null;
  /** Single Sign On/Unique Identifier of the User in Identity Management system */
  idMSSOID?: string | null;
  /** ISO culture code/ Language chosen by the logged in user */
  preferredLanguage?: string | null;
  /** Whether the user is a super administrator */
  isSuperAdmin?: boolean;
  /** Preferred Date format for the logged in user */
  dateFormat?: string | null;
  /** Preferred Time format for the logged in user */
  timeFormat?: string | null;
  /** Preferred Day to Begin the Week. The value will be between 1 to 7 or null. */
  weekBegins?: number | null;
  /** Preferred Display Week on Fuel Prices configuration for the logged in User. */
  displayWeek?: boolean;
  /** Preferred CSV Separator for the logged in user. */
  cSVSeparator?: string | null;
  /**
   * Preferred Decimal separator configured for the logged in user
   * Note: - Colco default value (configured at Microservices) is returned when the user is not provided or does not exist.
   */
  decimalSeparator?: string | null;
  /** Preferred report format configured for the logged in user */
  reportFormat?: string | null;
  /**
   * True/False
   * True, if user has access to the requested API. This is validated based on the role Vs API access matrix and client Vs API access matrix.
   */
  hasAPIAccess?: boolean;
  /** List of roles the user have access to */
  roles?: Role[];
  /**
   * List of payers which the user has access to.
   * •	It will return 250 payers only and it is configurable. If the user has more than that, the remaining will be ignored.
   * •	The payer which is marked as default will be the first item in the output.
   * Note: This list will be empty for users mapped with roles which has either IsShellAdmin or IsServiceAccount set to true as their access level is controlled at ColCo level only.
   */
  payers?: PayerAccess[];
  /**
   * List of accounts which the user has access to.
   * Note: This list will be empty for users mapped with roles which has either IsCustomerAdmin, IsShellAdmin or IsServiceAccount set to true as their access level is controller at either ColCo or payer level only.
   */
  accounts?: AccountAccess[];
  /**
   * List of collecting companies to which the user has access to
   * Note: This list will be empty for users mapped with roles which has either IsCustomerAdmin or IsCustomerUser set to true as their access level is controller at Payer or Account level.
   */
  collectingCompanies?: ColCoAccess[];
  /**
   * List of Electronic Invoice Data configured for the user.
   * Note: This list will be empty if the value of EIDDetails is set to false or empty in the request.
   */
  eIDAccessDetails?: EIDAccess[];
  /** User classification by system. */
  userClassificationBySystem?: string | null;
  /** User classification by Shell. */
  userClassificationByShell?: string | null;
  /**
   * Count of payers accessible to the user at the time when user was created or last updated.
   * Note:
   * Count may vary based on customer operations hence it may not be an up to date value.
   */
  payerCount?: number | null;
  /**
   * Count of accounts at the time when the user was created or last updated.
   * Note:
   * Count may vary based on customer operations hence it may not be an up to date value.
   */
  accountCount?: number | null;
  /**
   * Count of cards at the time when the user was created or last updated.
   * Note:
   * Count may vary based on customer operations hence it may not be an up to date value.
   */
  cardCount?: number | null;
  error?: ErrorStatus;
  /** Request Id of the API call */
  requestId?: string;
}

export const loggedInUserResponseSchema: Schema<LoggedInUserResponse> = object({
  userName: ['UserName', optional(nullable(string()))],
  displayName: ['DisplayName', optional(nullable(string()))],
  idMSSOID: ['IdMSSOID', optional(nullable(string()))],
  preferredLanguage: ['PreferredLanguage', optional(nullable(string()))],
  isSuperAdmin: ['IsSuperAdmin', optional(boolean())],
  dateFormat: ['DateFormat', optional(nullable(string()))],
  timeFormat: ['TimeFormat', optional(nullable(string()))],
  weekBegins: ['WeekBegins', optional(nullable(number()))],
  displayWeek: ['DisplayWeek', optional(boolean())],
  cSVSeparator: ['CSVSeparator', optional(nullable(string()))],
  decimalSeparator: ['DecimalSeparator', optional(nullable(string()))],
  reportFormat: ['ReportFormat', optional(nullable(string()))],
  hasAPIAccess: ['HasAPIAccess', optional(boolean())],
  roles: ['Roles', optional(array(lazy(() => roleSchema)))],
  payers: ['Payers', optional(array(lazy(() => payerAccessSchema)))],
  accounts: ['Accounts', optional(array(lazy(() => accountAccessSchema)))],
  collectingCompanies: [
    'CollectingCompanies',
    optional(array(lazy(() => colCoAccessSchema))),
  ],
  eIDAccessDetails: [
    'EIDAccessDetails',
    optional(array(lazy(() => eIDAccessSchema))),
  ],
  userClassificationBySystem: [
    'UserClassificationBySystem',
    optional(nullable(string())),
  ],
  userClassificationByShell: [
    'UserClassificationByShell',
    optional(nullable(string())),
  ],
  payerCount: ['PayerCount', optional(nullable(number()))],
  accountCount: ['AccountCount', optional(nullable(number()))],
  cardCount: ['CardCount', optional(nullable(number()))],
  error: ['Error', optional(lazy(() => errorStatusSchema))],
  requestId: ['RequestId', optional(string())],
});
