/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { ErrorStatus, errorStatusSchema } from './errorStatus';
import {
  MultiPricedTransactionResponseTransactionsItems,
  multiPricedTransactionResponseTransactionsItemsSchema,
} from './multiPricedTransactionResponseTransactionsItems';

export interface MultiPricedTransactionResponse {
  transactions?: MultiPricedTransactionResponseTransactionsItems[];
  error?: ErrorStatus;
  /** API Request Id */
  requestId?: string;
  /** Current Page */
  currentPage?: number;
  /** Total row count matched for the given input criteria */
  rowCount?: number;
  /** Calculated page count based on page size from the incoming API request and total number of rows matched for the given input criteria */
  totalPages?: number;
}

export const multiPricedTransactionResponseSchema: Schema<MultiPricedTransactionResponse> = object(
  {
    transactions: [
      'Transactions',
      optional(
        array(lazy(() => multiPricedTransactionResponseTransactionsItemsSchema))
      ),
    ],
    error: ['Error', optional(lazy(() => errorStatusSchema))],
    requestId: ['RequestId', optional(string())],
    currentPage: ['CurrentPage', optional(number())],
    rowCount: ['RowCount', optional(number())],
    totalPages: ['TotalPages', optional(number())],
  }
);
