/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  MultiPricedTransactionResponseTransactionsItems,
  multiPricedTransactionResponseTransactionsItemsSchema,
} from './multiPricedTransactionResponseTransactionsItems.js';

export interface MultiPricedTransactionResponse {
  transactions?: MultiPricedTransactionResponseTransactionsItems[];
}

export const multiPricedTransactionResponseSchema: Schema<MultiPricedTransactionResponse> = object(
  {
    transactions: [
      'Transactions',
      optional(
        array(lazy(() => multiPricedTransactionResponseTransactionsItemsSchema))
      ),
    ],
  }
);
