/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface PastStatementOfAccounts {
  /** Invoiced amount under this statement of account and due for payment. */
  amountDue?: number | null;
  /** Total Invoiced amount until this SOA and not overdue for payment. */
  amountNotOverdue?: number | null;
  /** Overdue amount from the previously generated statement of accounts. */
  amountOverdue?: number | null;
  /** Overdue amount calculated from unallocated payment. */
  amountOverdueFromUnallocated?: number | null;
  /** Amount settled for this Statement. */
  amountPaid?: number | null;
  /** Balance amount to be settled on this SOA. */
  balanceOnThisStatement?: number | null;
  /**
   * Billing currency ISO code.
   * Example: EUR
   */
  billingCurrencyCode?: string | null;
  /**
   * Billing currency symbol.
   * Example: €
   */
  billingCurrencySymbol?: string | null;
  /** Credit limit. */
  creditLimit?: number | null;
  /**
   * ISO code of the credit limit’s currency.
   * Example: EUR
   */
  creditLimitCurrencyCode?: string | null;
  /**
   * Symbol of the credit limit’s currency.
   * Example: €
   */
  creditLimitCurrencySymbol?: string | null;
  /**
   * Credit limit in Customer currency.
   * Note: For currency details refer the parameters CurrencyCode & CurrencySymbol in the SOADetail response.
   */
  creditLimitInCustomerCurrency?: number | null;
  /**
   * ISO code of SOA currency.
   * Example: EUR
   */
  currencyCode?: string | null;
  /**
   * Symbol of SOA currency.
   * Example: €
   */
  currencySymbol?: string | null;
  /** True If all summary billing documents under this SOA are fully paid (i.e., the fully paid flag is set to true for all documents or the amount allocated is greater than or equal to the amount due under this SOA. */
  fullyPaid?: boolean | null;
  /**
   * ISO code of last payment currency.
   * Example: EUR
   */
  lastPaymentCurrencyCode?: string | null;
  /**
   * Symbol of last payment currency.
   * Example: €
   */
  lastPaymentCurrencySymbol?: string | null;
  /** Last payment date. Format: yyyyMMdd */
  lastPaymentDate?: string | null;
  /** Last payment value. */
  lastPaymentValue?: number | null;
  /** Total outstanding balance at the time of this SOA generation. */
  outstandingBalance?: number | null;
  /** Payment customer id of the customer. */
  payerId?: number | null;
  /** Payment customer number. */
  payerNumber?: string | null;
  /** Due date for payment. Format: yyyyMMdd */
  paymentDueDate?: string | null;
  /** Statement of account reference number. */
  soAReferenceNumber?: string | null;
  /**
   * Date on which the SOA was generated.
   * Format: yyyyMMdd
   */
  statementDate?: string | null;
  /** Statement of account identifier, */
  statementOfAccountId?: number | null;
  /** Total number of billing documents generated under this Statement of Account. */
  totalBillingDocuments?: number | null;
  /** Total NET amount from all billing documents in this SOA. */
  totalNetAmountBillingCurrency?: number | null;
  /** Total number of summary billing documents for this Statement of Account */
  totalSummaryBillingDocuments?: number | null;
  /** Total VAT amount from all billing documents in this SOA. */
  totalVATAmountBillingCurrency?: number | null;
  /** Amount paid but not allocated to any invoices at the time of this SOA generation. */
  unallocatedPayment?: number | null;
  /**
   * Currency ISO code of the local country. It is derived based on CountryCode from microservice configuration. This field is expected to have different value than the previously mentioned field CurrencyCode, only in the case of serviced OUs.
   * Example: EUR
   */
  localCurrencyCode?: string | null;
  /**
   * Currency Symbol of the local country. It is derived based on CountryCode from microservice configuration. This field is expected to have different value than the previously mentioned field CurrencySymbol, only in the case of serviced OUs.
   * Example: €
   */
  localCurrencySymbol?: string | null;
  /**
   * Exchange rate from Billing currency to local currency.
   * Example: 1.2
   */
  localCurrencyExchangeRate?: number | null;
}

export const pastStatementOfAccountsSchema: Schema<PastStatementOfAccounts> = object(
  {
    amountDue: ['AmountDue', optional(nullable(number()))],
    amountNotOverdue: ['AmountNotOverdue', optional(nullable(number()))],
    amountOverdue: ['AmountOverdue', optional(nullable(number()))],
    amountOverdueFromUnallocated: [
      'AmountOverdueFromUnallocated',
      optional(nullable(number())),
    ],
    amountPaid: ['AmountPaid', optional(nullable(number()))],
    balanceOnThisStatement: [
      'BalanceOnThisStatement',
      optional(nullable(number())),
    ],
    billingCurrencyCode: ['BillingCurrencyCode', optional(nullable(string()))],
    billingCurrencySymbol: [
      'BillingCurrencySymbol',
      optional(nullable(string())),
    ],
    creditLimit: ['CreditLimit', optional(nullable(number()))],
    creditLimitCurrencyCode: [
      'CreditLimitCurrencyCode',
      optional(nullable(string())),
    ],
    creditLimitCurrencySymbol: [
      'CreditLimitCurrencySymbol',
      optional(nullable(string())),
    ],
    creditLimitInCustomerCurrency: [
      'CreditLimitInCustomerCurrency',
      optional(nullable(number())),
    ],
    currencyCode: ['CurrencyCode', optional(nullable(string()))],
    currencySymbol: ['CurrencySymbol', optional(nullable(string()))],
    fullyPaid: ['FullyPaid', optional(nullable(boolean()))],
    lastPaymentCurrencyCode: [
      'LastPaymentCurrencyCode',
      optional(nullable(string())),
    ],
    lastPaymentCurrencySymbol: [
      'LastPaymentCurrencySymbol',
      optional(nullable(string())),
    ],
    lastPaymentDate: ['LastPaymentDate', optional(nullable(string()))],
    lastPaymentValue: ['LastPaymentValue', optional(nullable(number()))],
    outstandingBalance: ['OutstandingBalance', optional(nullable(number()))],
    payerId: ['PayerId', optional(nullable(number()))],
    payerNumber: ['PayerNumber', optional(nullable(string()))],
    paymentDueDate: ['PaymentDueDate', optional(nullable(string()))],
    soAReferenceNumber: ['SoAReferenceNumber', optional(nullable(string()))],
    statementDate: ['StatementDate', optional(nullable(string()))],
    statementOfAccountId: [
      'StatementOfAccountId',
      optional(nullable(number())),
    ],
    totalBillingDocuments: [
      'TotalBillingDocuments',
      optional(nullable(number())),
    ],
    totalNetAmountBillingCurrency: [
      'TotalNetAmountBillingCurrency',
      optional(nullable(number())),
    ],
    totalSummaryBillingDocuments: [
      'TotalSummaryBillingDocuments',
      optional(nullable(number())),
    ],
    totalVATAmountBillingCurrency: [
      'TotalVATAmountBillingCurrency',
      optional(nullable(number())),
    ],
    unallocatedPayment: ['UnallocatedPayment', optional(nullable(number()))],
    localCurrencyCode: ['LocalCurrencyCode', optional(nullable(string()))],
    localCurrencySymbol: ['LocalCurrencySymbol', optional(nullable(string()))],
    localCurrencyExchangeRate: [
      'LocalCurrencyExchangeRate',
      optional(nullable(number())),
    ],
  }
);
