/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, nullable, number, object, optional, Schema } from '../schema.js';
import { PayerRequest, payerRequestSchema } from './payerRequest.js';

export interface PayerReq {
  filters?: PayerRequest;
  /** Page Number (as shown to the users) */
  page?: number | null;
  /** Page Size – Number of records to show on a page. */
  pageSize?: number | null;
}

export const payerReqSchema: Schema<PayerReq> = lazy(() =>
  object({
    filters: ['Filters', optional(payerRequestSchema)],
    page: ['Page', optional(nullable(number()))],
    pageSize: ['PageSize', optional(nullable(number()))],
  })
);
