/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PricedTransactionReqV2InvoiceStatusEnum
 */
export enum PricedTransactionReqV2InvoiceStatusEnum {
  I = 'I',
  U = 'U',
  A = 'A',
}

/**
 * Schema for PricedTransactionReqV2InvoiceStatusEnum
 */
export const pricedTransactionReqV2InvoiceStatusEnumSchema: Schema<PricedTransactionReqV2InvoiceStatusEnum> = stringEnum(
  PricedTransactionReqV2InvoiceStatusEnum
);
