/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema';

/**
 * Enum for PricedTransactionReqV2SortOrderEnum
 */
export enum PricedTransactionReqV2SortOrderEnum {
  Enum1 = '1',
  Enum2 = '2',
  Enum3 = '3',
  Enum4 = '4',
  Enum5 = '5',
  Enum6 = '6',
}

/**
 * Schema for PricedTransactionReqV2SortOrderEnum
 */
export const pricedTransactionReqV2SortOrderEnumSchema: Schema<PricedTransactionReqV2SortOrderEnum> = stringEnum(
  PricedTransactionReqV2SortOrderEnum
);
