/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  PriceTransSummaryRequest,
  priceTransSummaryRequestSchema,
} from './priceTransSummaryRequest.js';

export interface PriceTransSummaryReq {
  filters?: PriceTransSummaryRequest;
}

export const priceTransSummaryReqSchema: Schema<PriceTransSummaryReq> = object({
  filters: ['Filters', optional(lazy(() => priceTransSummaryRequestSchema))],
});
