/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  PricedTransactionRespV2RefundFlagEnum,
  pricedTransactionRespV2RefundFlagEnumSchema,
} from './pricedTransactionRespV2RefundFlagEnum';

export interface PricedResponseData {
  /** Name of the account */
  accountName?: string | null;
  /** Account Id (i.e. Customer Id of the Sub Account in GFN) of the selected account. */
  accountId?: number | null;
  /** AccountNumber of the selected account. */
  accountNumber?: string | null;
  /** Nick name of the account */
  accountShortName?: string | null;
  /** Addtional SerialId or endpoint Id */
  additional1?: string | null;
  /** Addtional SerialId or endpoint Id */
  additional2?: string | null;
  /** Addtional SerialId or endpoint Id */
  additional3?: string | null;
  /** Addtional SerialId or endpoint Id */
  additional4?: string | null;
  /** Allow clearings */
  allowClearing?: string | null;
  /** Autorization code */
  authorisationCode?: number | null;
  /** Status of the transaction */
  transactionStatus?: string | null;
  /** Driver Name of Card record */
  driverName?: string | null;
  /** Expiry period of the card */
  cardExpiryPeriod?: number | null;
  /** Card Expiry Date */
  cardExpiry?: string | null;
  /** Card Group Code */
  cardGroupId?: number | null;
  /** Group nmae of the card */
  cardGroupName?: string | null;
  /** Issuer code */
  issuerCode?: number | null;
  /** Full Card PAN */
  cardPAN?: string | null;
  /** Release code */
  releaseCode?: number | null;
  /** Sequesnce number of the card */
  cardSequenceNumber?: number | null;
  /** Type of card */
  cardType?: string | null;
  /** Collecting Company Code (Shell Code) of the selected payer. */
  colCoCode?: string | null;
  /** Unit discount Invoice currency */
  unitDiscountInvoiceCurrency?: number | null;
  /** Colco exchange rate */
  colCoExchangeRate?: number;
  /** Currency symbol on which the invoice was raised */
  invoiceCurrencySymbol?: string | null;
  /** Is there any correction */
  correctionFlag?: boolean | null;
  /** CRM number */
  cRMNumber?: number | null;
  /** Customer country */
  customerCountry?: string | null;
  /** Curreny which customer uses to transact. */
  customerCurrencyCode?: string | null;
  /** Custome currency symbol */
  customerCurrencySymbol?: string | null;
  /** Rebate on net amount in customer currency */
  rebateonNetAmountInCustomerCurrency?: number | null;
  /** Effective discount in customers currency */
  effectiveDiscountInCustomerCurrency?: number | null;
  /** effectiive unit discount in customers currency */
  effectiveUnitDiscountInCustomerCurrency?: number | null;
  /** Unitpricing in invoice currency */
  unitPriceInInvoiceCurrency?: number | null;
  /** Invoice tax */
  invoiceTax?: number | null;
  /** Invoice amount befor tax */
  invoiceGrossAmount?: number | null;
  /** Invoice amount after tax */
  invoiceNetAmount?: number | null;
  /** Vat on net amount in customer currency */
  vATonNetAmountInCustomerCurrency?: number | null;
  /** Customer retail unit price before tax */
  customerRetailPriceUnitGross?: number | null;
  /** Total Customer retail value before tax */
  customerRetailValueTotalGross?: number | null;
  /** Total customer retail value after tax */
  customerRetailValueTotalNet?: number | null;
  /** Trasaction type description */
  transactionTypeDescription?: number | null;
  /** Rebate give to net amountin transaction currency that is used */
  rebateonNetAmountInTransactionCurrency?: number | null;
  /** Currency used to giveEffective discount on transactions */
  effectiveDiscountInTrxCurrency?: number | null;
  /** Exchange rate between Delco and Colco */
  delCoToColCoExchangeRate?: number | null;
  cards?: number[];
  /** Currency used forto provide unit Transaction discount */
  unitDiscountTransactionCurrency?: number | null;
  /** Transactional amount before tax */
  transactionGrossAmount?: number | null;
  /** Transaction net amount after tax */
  transactionNetAmount?: number | null;
  /** Transaction tax */
  transactionTax?: number | null;
  /** Transactinal tax rates */
  vATonNetAmount?: number | null;
  /** Priv */
  delcoListPriceUnitNet?: number | null;
  /** Delco retail price per unit before tax */
  delcoRetailPriceUnitGross?: number | null;
  /** Delco retail price per unit after tax */
  unitPriceInTransactionCurrency?: number | null;
  /** Delco retail price per unit */
  delcoRetailPriceUnitNet?: number | null;
  /** Delco retail price before tax */
  delcoRetailValueTotalGross?: number | null;
  /** Delco per unit price after tax */
  delcoRetailValueTotalNet?: number | null;
  /** Currency used for transaction. */
  transactionCurrencySymbol?: string | null;
  /** Type of discount available */
  discountType?: string | null;
  /** Is there any dispute status?True or False */
  disputeStatus?: boolean | null;
  /** Is it a shell sites?True or False */
  isShellSite?: boolean;
  /** Fleet identifier */
  fleetIdInput?: string | null;
  /** In coming product code */
  incomingProductCode?: number | null;
  /** Date of Posting */
  postingDate?: string | null;
  /** Time whern posting happened */
  postingTime?: string | null;
  /** Product Code - 21 Unleaded - High octane,22 Unleaded - Medium octane,23 Unleaded - Low octane,24 Unleaded Environmental */
  productCode?: number | null;
  /** Name of the product */
  productName?: string | null;
  /** Id of the product to which group it belongs */
  productGroupId?: number | null;
  /** In coming currecncy code */
  incomingCurrencyCode?: string | null;
  /** In coming Site description */
  incomingSiteDescription?: string | null;
  /** Location of the Shell site */
  location?: string | null;
  /** Shell site name */
  siteName?: string | null;
  /** Shell site code */
  siteCode?: number | null;
  /** In coming site number */
  incomingSiteNumber?: number | null;
  /** Currency code on which the invoice is raised */
  invoiceCurrencyCode?: string | null;
  /** Date on which the invoice was raised */
  invoiceDate?: string | null;
  /** Invoice number */
  invoiceNumber?: number | null;
  /** Is it a fuel product? True or False */
  fuelProduct?: boolean | null;
  /** Is VAT applicable?Y or N */
  vATApplicable?: string | null;
  /** Name of the payer */
  payerName?: string | null;
  /** Payer account number */
  payerNumber?: string | null;
  /** Parent account number of the payer */
  parentCustomerNumber?: string | null;
  /** The group which the payer belongs to */
  payerGroup?: string | null;
  /** Name of the group to which the payer belongs to. */
  payerGroupName?: string | null;
  /** Check digit */
  checkDigit?: number | null;
  /** After tax net invoice number */
  netInvoiceIndicator?: string | null;
  /** Delco code */
  delcoCode?: number | null;
  /** Network  code of the payer */
  networkCode?: number | null;
  /** Country of purchase */
  purchasedInCountry?: string | null;
  /** Country where the site exists */
  siteCountry?: string | null;
  /** Country where VAT is applicable */
  vATCountry?: string | null;
  /** Name of the delivery company */
  delcoName?: string | null;
  /** Network of the Delivery company */
  network?: string | null;
  /** Odometet input */
  odometerInput?: number | null;
  /** Original item identifier for sales */
  originalSalesItemId?: string | null;
  /** Fleet identifier description */
  fleetIDDescription?: string | null;
  /** Identifier of parent customer */
  parentCustomerId?: number | null;
  /** PIN indicator */
  pINIndicator?: string | null;
  /** Name og the group the product belongs to */
  productGroupName?: string | null;
  /** The countroy code where the purchase was made */
  purchasedInCountryCode?: string | null;
  /** Quantity of the product */
  quantity?: number | null;
  /** Rebate rate if any */
  rebateRate?: number | null;
  /** Reciept number */
  receiptNumber?: number | null;
  /** Flag to check if there is any refund */
  refundFlag?: PricedTransactionRespV2RefundFlagEnum;
  /** Group identifier for the site */
  siteGroupId?: number | null;
  /** Name of the Site group */
  siteGroupName?: string | null;
  /** Latitude of the site */
  latitude?: number | null;
  /** Longitude of the site */
  longitude?: number | null;
  /** Delivery company exchange rate */
  delCoExchangeRate?: number | null;
  /** Rebate amount in Euros */
  euroRebateAmount?: number | null;
  /** Net amount in Euros */
  netEuroAmount?: number | null;
  /** Vat amount in Euros */
  euroVATAmount?: number | null;
  /** Customers parent name */
  parentCustomerName?: string | null;
  /** Is invoice raised */
  isInvoiced?: boolean | null;
  /** Transaction currency code */
  transactionCurrencyCode?: string | null;
  /** Is it Credit or debit C for credit D for Debit */
  creditDebitCode?: string | null;
  /** Date of transaction */
  transactionDate?: string | null;
  /** Time of transaction */
  transactionTime?: string | null;
  /** Identifier of the Iem in transaction */
  transactionItemId?: string | null;
  /** Transaction identifier */
  trnIdentifier?: string | null;
  /** Transaction type for Delco */
  type?: string | null;
  transactionLine?: number | null;
  /** Transaction type Colco */
  transactionType?: string | null;
  /** Leaving country */
  uTCOffset?: string | null;
  /** To which category and counry does the  VAT come under */
  vATCategory?: string | null;
  /** VAT rate */
  vATRate?: number | null;
  /** Vehicle registration number */
  vehicleRegistration?: string | null;
  /** Check if the pruchase is cancelled */
  isCancelled?: string | null;
  /** Gross amount from Colco */
  colCoGrossAmount?: number | null;
  /** Net amount from Colco */
  colCoNetAmount?: number | null;
  /** Colco VAT amount */
  colCoVATAmount?: number | null;
  /** Original currency code */
  originalCurrencySymbol?: string | null;
  /** Original currency code */
  originalCurrencyCode?: string | null;
  /** Original VAT amount */
  originalVATAmount?: number | null;
  /** Comapany name embosses in text */
  embossText?: string | null;
  /** Orginal exchange rate */
  originalExchangeRate?: number | null;
  /** Original treansaction date */
  originalTransactionItemInvoiceDate?: string | null;
  /** Fee type identifier */
  feeTypeId?: number | null;
  /** Line item identifier of the product */
  lineItemDescription?: boolean | null;
  /** Fee rule description */
  feeRuleDescription?: string | null;
  /** Frequency of transaction */
  frequency?: number | null;
  /** Fee rule identifier */
  feeRuleId?: number | null;
  /** Entry date in the system */
  systemEntryDate?: string | null;
  /** Entry time in the system */
  systemEntryTime?: string | null;
  /** Checking if its manual */
  isManual?: string | null;
  /** Is it manual */
  originalTransactionItemId?: string | null;
  /** Original invoice transaction number */
  originalTransactionItemInvoiceNumber?: number | null;
  /** Original Invoice transaction Identifier */
  originalTransactionItemInvoiceId?: number | null;
  /** Payers short name */
  payerShortName?: string | null;
  /** Is reverse charge? */
  reverseCharge?: string | null;
  /** Original gross amount */
  originalGrossAmount?: number | null;
  /** Original Net amount */
  originalNetAmount?: number | null;
  /** Unit of measure */
  unitOfMeasure?: string | null;
  /** Type of road */
  roadType?: string | null;
  /** Customer country ISO Code */
  customerCountryIsoCode?: string | null;
  /** EvOperator Name */
  eVOperator?: string | null;
  /** Ev Operator identifier */
  eVSerialId?: string | null;
  /** EV Charging point iserial identifier */
  eVChargePointSerial?: string | null;
  /** Ev chariging connector type */
  eVChargePointConnectorType?: number | null;
  /** EV charging point connector type description */
  eVChargePointConnectorTypeDescription?: string | null;
  /** Ev charging Duration */
  eVChargeDuration?: string | null;
  /** EvCharging start Date */
  eVChargeStartDate?: string | null;
  /** EvCharging start time */
  eVChargeStartTime?: string | null;
  /** EvCharging End Date */
  eVChargeEndDate?: string | null;
  /** EvCharging End time */
  eVChargeEndTime?: string | null;
  hostingCollectingCompanyNumber?: number | null;
  transactionId?: number | null;
  fuelOnly?: boolean | null;
}

export const pricedResponseDataSchema: Schema<PricedResponseData> = object({
  accountName: ['AccountName', optional(nullable(string()))],
  accountId: ['AccountId', optional(nullable(number()))],
  accountNumber: ['AccountNumber', optional(nullable(string()))],
  accountShortName: ['AccountShortName', optional(nullable(string()))],
  additional1: ['Additional1', optional(nullable(string()))],
  additional2: ['Additional2', optional(nullable(string()))],
  additional3: ['Additional3', optional(nullable(string()))],
  additional4: ['Additional4', optional(nullable(string()))],
  allowClearing: ['AllowClearing', optional(nullable(string()))],
  authorisationCode: ['AuthorisationCode', optional(nullable(number()))],
  transactionStatus: ['TransactionStatus', optional(nullable(string()))],
  driverName: ['DriverName', optional(nullable(string()))],
  cardExpiryPeriod: ['CardExpiryPeriod', optional(nullable(number()))],
  cardExpiry: ['CardExpiry', optional(nullable(string()))],
  cardGroupId: ['CardGroupId', optional(nullable(number()))],
  cardGroupName: ['CardGroupName', optional(nullable(string()))],
  issuerCode: ['IssuerCode', optional(nullable(number()))],
  cardPAN: ['CardPAN', optional(nullable(string()))],
  releaseCode: ['ReleaseCode', optional(nullable(number()))],
  cardSequenceNumber: ['CardSequenceNumber', optional(nullable(number()))],
  cardType: ['CardType', optional(nullable(string()))],
  colCoCode: ['ColCoCode', optional(nullable(string()))],
  unitDiscountInvoiceCurrency: [
    'UnitDiscountInvoiceCurrency',
    optional(nullable(number())),
  ],
  colCoExchangeRate: ['ColCoExchangeRate', optional(number())],
  invoiceCurrencySymbol: [
    'InvoiceCurrencySymbol',
    optional(nullable(string())),
  ],
  correctionFlag: ['CorrectionFlag', optional(nullable(boolean()))],
  cRMNumber: ['CRMNumber', optional(nullable(number()))],
  customerCountry: ['CustomerCountry', optional(nullable(string()))],
  customerCurrencyCode: ['CustomerCurrencyCode', optional(nullable(string()))],
  customerCurrencySymbol: [
    'CustomerCurrencySymbol',
    optional(nullable(string())),
  ],
  rebateonNetAmountInCustomerCurrency: [
    'RebateonNetAmountInCustomerCurrency',
    optional(nullable(number())),
  ],
  effectiveDiscountInCustomerCurrency: [
    'EffectiveDiscountInCustomerCurrency',
    optional(nullable(number())),
  ],
  effectiveUnitDiscountInCustomerCurrency: [
    'EffectiveUnitDiscountInCustomerCurrency',
    optional(nullable(number())),
  ],
  unitPriceInInvoiceCurrency: [
    'UnitPriceInInvoiceCurrency',
    optional(nullable(number())),
  ],
  invoiceTax: ['InvoiceTax', optional(nullable(number()))],
  invoiceGrossAmount: ['InvoiceGrossAmount', optional(nullable(number()))],
  invoiceNetAmount: ['InvoiceNetAmount', optional(nullable(number()))],
  vATonNetAmountInCustomerCurrency: [
    'VATonNetAmountInCustomerCurrency',
    optional(nullable(number())),
  ],
  customerRetailPriceUnitGross: [
    'CustomerRetailPriceUnitGross',
    optional(nullable(number())),
  ],
  customerRetailValueTotalGross: [
    'CustomerRetailValueTotalGross',
    optional(nullable(number())),
  ],
  customerRetailValueTotalNet: [
    'CustomerRetailValueTotalNet',
    optional(nullable(number())),
  ],
  transactionTypeDescription: [
    'TransactionTypeDescription',
    optional(nullable(number())),
  ],
  rebateonNetAmountInTransactionCurrency: [
    'RebateonNetAmountInTransactionCurrency',
    optional(nullable(number())),
  ],
  effectiveDiscountInTrxCurrency: [
    'EffectiveDiscountInTrxCurrency',
    optional(nullable(number())),
  ],
  delCoToColCoExchangeRate: [
    'DelCoToColCoExchangeRate',
    optional(nullable(number())),
  ],
  cards: ['Cards', optional(array(number()))],
  unitDiscountTransactionCurrency: [
    'UnitDiscountTransactionCurrency',
    optional(nullable(number())),
  ],
  transactionGrossAmount: [
    'TransactionGrossAmount',
    optional(nullable(number())),
  ],
  transactionNetAmount: ['TransactionNetAmount', optional(nullable(number()))],
  transactionTax: ['TransactionTax', optional(nullable(number()))],
  vATonNetAmount: ['VATonNetAmount', optional(nullable(number()))],
  delcoListPriceUnitNet: [
    'DelcoListPriceUnitNet',
    optional(nullable(number())),
  ],
  delcoRetailPriceUnitGross: [
    'DelcoRetailPriceUnitGross',
    optional(nullable(number())),
  ],
  unitPriceInTransactionCurrency: [
    'UnitPriceInTransactionCurrency',
    optional(nullable(number())),
  ],
  delcoRetailPriceUnitNet: [
    'DelcoRetailPriceUnitNet',
    optional(nullable(number())),
  ],
  delcoRetailValueTotalGross: [
    'DelcoRetailValueTotalGross',
    optional(nullable(number())),
  ],
  delcoRetailValueTotalNet: [
    'DelcoRetailValueTotalNet',
    optional(nullable(number())),
  ],
  transactionCurrencySymbol: [
    'TransactionCurrencySymbol',
    optional(nullable(string())),
  ],
  discountType: ['DiscountType', optional(nullable(string()))],
  disputeStatus: ['DisputeStatus', optional(nullable(boolean()))],
  isShellSite: ['IsShellSite', optional(boolean())],
  fleetIdInput: ['FleetIdInput', optional(nullable(string()))],
  incomingProductCode: ['IncomingProductCode', optional(nullable(number()))],
  postingDate: ['PostingDate', optional(nullable(string()))],
  postingTime: ['PostingTime', optional(nullable(string()))],
  productCode: ['ProductCode', optional(nullable(number()))],
  productName: ['ProductName', optional(nullable(string()))],
  productGroupId: ['ProductGroupId', optional(nullable(number()))],
  incomingCurrencyCode: ['IncomingCurrencyCode', optional(nullable(string()))],
  incomingSiteDescription: [
    'IncomingSiteDescription',
    optional(nullable(string())),
  ],
  location: ['Location', optional(nullable(string()))],
  siteName: ['SiteName', optional(nullable(string()))],
  siteCode: ['SiteCode', optional(nullable(number()))],
  incomingSiteNumber: ['IncomingSiteNumber', optional(nullable(number()))],
  invoiceCurrencyCode: ['InvoiceCurrencyCode', optional(nullable(string()))],
  invoiceDate: ['InvoiceDate', optional(nullable(string()))],
  invoiceNumber: ['InvoiceNumber', optional(nullable(number()))],
  fuelProduct: ['FuelProduct', optional(nullable(boolean()))],
  vATApplicable: ['VATApplicable', optional(nullable(string()))],
  payerName: ['PayerName', optional(nullable(string()))],
  payerNumber: ['PayerNumber', optional(nullable(string()))],
  parentCustomerNumber: ['ParentCustomerNumber', optional(nullable(string()))],
  payerGroup: ['PayerGroup', optional(nullable(string()))],
  payerGroupName: ['PayerGroupName', optional(nullable(string()))],
  checkDigit: ['CheckDigit', optional(nullable(number()))],
  netInvoiceIndicator: ['NetInvoiceIndicator', optional(nullable(string()))],
  delcoCode: ['DelcoCode', optional(nullable(number()))],
  networkCode: ['NetworkCode', optional(nullable(number()))],
  purchasedInCountry: ['PurchasedInCountry', optional(nullable(string()))],
  siteCountry: ['SiteCountry', optional(nullable(string()))],
  vATCountry: ['VATCountry', optional(nullable(string()))],
  delcoName: ['DelcoName', optional(nullable(string()))],
  network: ['Network', optional(nullable(string()))],
  odometerInput: ['OdometerInput', optional(nullable(number()))],
  originalSalesItemId: ['OriginalSalesItemId', optional(nullable(string()))],
  fleetIDDescription: ['FleetIDDescription', optional(nullable(string()))],
  parentCustomerId: ['ParentCustomerId', optional(nullable(number()))],
  pINIndicator: ['PINIndicator', optional(nullable(string()))],
  productGroupName: ['ProductGroupName', optional(nullable(string()))],
  purchasedInCountryCode: [
    'PurchasedInCountryCode',
    optional(nullable(string())),
  ],
  quantity: ['Quantity', optional(nullable(number()))],
  rebateRate: ['RebateRate', optional(nullable(number()))],
  receiptNumber: ['ReceiptNumber', optional(nullable(number()))],
  refundFlag: [
    'RefundFlag',
    optional(pricedTransactionRespV2RefundFlagEnumSchema),
  ],
  siteGroupId: ['SiteGroupId', optional(nullable(number()))],
  siteGroupName: ['SiteGroupName', optional(nullable(string()))],
  latitude: ['Latitude', optional(nullable(number()))],
  longitude: ['Longitude', optional(nullable(number()))],
  delCoExchangeRate: ['DelCoExchangeRate', optional(nullable(number()))],
  euroRebateAmount: ['EuroRebateAmount', optional(nullable(number()))],
  netEuroAmount: ['NetEuroAmount', optional(nullable(number()))],
  euroVATAmount: ['EuroVATAmount', optional(nullable(number()))],
  parentCustomerName: ['ParentCustomerName', optional(nullable(string()))],
  isInvoiced: ['IsInvoiced', optional(nullable(boolean()))],
  transactionCurrencyCode: [
    'TransactionCurrencyCode',
    optional(nullable(string())),
  ],
  creditDebitCode: ['CreditDebitCode', optional(nullable(string()))],
  transactionDate: ['TransactionDate', optional(nullable(string()))],
  transactionTime: ['TransactionTime', optional(nullable(string()))],
  transactionItemId: ['TransactionItemId', optional(nullable(string()))],
  trnIdentifier: ['TrnIdentifier', optional(nullable(string()))],
  type: ['Type', optional(nullable(string()))],
  transactionLine: ['TransactionLine', optional(nullable(number()))],
  transactionType: ['TransactionType', optional(nullable(string()))],
  uTCOffset: ['UTCOffset', optional(nullable(string()))],
  vATCategory: ['VATCategory', optional(nullable(string()))],
  vATRate: ['VATRate', optional(nullable(number()))],
  vehicleRegistration: ['VehicleRegistration', optional(nullable(string()))],
  isCancelled: ['IsCancelled', optional(nullable(string()))],
  colCoGrossAmount: ['ColCoGrossAmount', optional(nullable(number()))],
  colCoNetAmount: ['ColCoNetAmount', optional(nullable(number()))],
  colCoVATAmount: ['ColCoVATAmount', optional(nullable(number()))],
  originalCurrencySymbol: [
    'OriginalCurrencySymbol',
    optional(nullable(string())),
  ],
  originalCurrencyCode: ['OriginalCurrencyCode', optional(nullable(string()))],
  originalVATAmount: ['OriginalVATAmount', optional(nullable(number()))],
  embossText: ['EmbossText', optional(nullable(string()))],
  originalExchangeRate: ['OriginalExchangeRate', optional(nullable(number()))],
  originalTransactionItemInvoiceDate: [
    'OriginalTransactionItemInvoiceDate',
    optional(nullable(string())),
  ],
  feeTypeId: ['FeeTypeId', optional(nullable(number()))],
  lineItemDescription: ['LineItemDescription', optional(nullable(boolean()))],
  feeRuleDescription: ['FeeRuleDescription', optional(nullable(string()))],
  frequency: ['Frequency', optional(nullable(number()))],
  feeRuleId: ['FeeRuleId', optional(nullable(number()))],
  systemEntryDate: ['SystemEntryDate', optional(nullable(string()))],
  systemEntryTime: ['SystemEntryTime', optional(nullable(string()))],
  isManual: ['IsManual', optional(nullable(string()))],
  originalTransactionItemId: [
    'OriginalTransactionItemId',
    optional(nullable(string())),
  ],
  originalTransactionItemInvoiceNumber: [
    'OriginalTransactionItemInvoiceNumber',
    optional(nullable(number())),
  ],
  originalTransactionItemInvoiceId: [
    'OriginalTransactionItemInvoiceId',
    optional(nullable(number())),
  ],
  payerShortName: ['PayerShortName', optional(nullable(string()))],
  reverseCharge: ['ReverseCharge', optional(nullable(string()))],
  originalGrossAmount: ['OriginalGrossAmount', optional(nullable(number()))],
  originalNetAmount: ['OriginalNetAmount', optional(nullable(number()))],
  unitOfMeasure: ['UnitOfMeasure', optional(nullable(string()))],
  roadType: ['RoadType', optional(nullable(string()))],
  customerCountryIsoCode: [
    'CustomerCountryIsoCode',
    optional(nullable(string())),
  ],
  eVOperator: ['EVOperator', optional(nullable(string()))],
  eVSerialId: ['EVSerialId', optional(nullable(string()))],
  eVChargePointSerial: ['EVChargePointSerial', optional(nullable(string()))],
  eVChargePointConnectorType: [
    'EVChargePointConnectorType',
    optional(nullable(number())),
  ],
  eVChargePointConnectorTypeDescription: [
    'EVChargePointConnectorTypeDescription',
    optional(nullable(string())),
  ],
  eVChargeDuration: ['EVChargeDuration', optional(nullable(string()))],
  eVChargeStartDate: ['EVChargeStartDate', optional(nullable(string()))],
  eVChargeStartTime: ['EVChargeStartTime', optional(nullable(string()))],
  eVChargeEndDate: ['EVChargeEndDate', optional(nullable(string()))],
  eVChargeEndTime: ['EVChargeEndTime', optional(nullable(string()))],
  hostingCollectingCompanyNumber: [
    'HostingCollectingCompanyNumber',
    optional(nullable(number())),
  ],
  transactionId: ['TransactionId', optional(nullable(number()))],
  fuelOnly: ['FuelOnly', optional(nullable(boolean()))],
});
