/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface RecentTransactionReq {
  /** Three character Collecting Company Code (Shell Code) of the selected payer */
  colCoCode: number | null;
  /** Unique Identifier for the customer at payment point. */
  payerNumber: string | null;
  /** Customer account number. */
  accountNumber?: string | null;
  /** Global product code */
  productCode?: string | null;
  /** Delco country */
  purchasedInCountry?: string | null;
  /** Card identifier number masked */
  cardPAN?: string | null;
  /** Start date and time of transactions */
  fromDateTime?: string | null;
  /** End date and time of transactions. Mandatory if FromDateTime is provided. */
  toDateTime?: string | null;
  /** Status of transaction. DO NOT pass the value if includeDeclines is passed */
  transactionStatus?: string | null;
  /** When passed as ‘true’ Only returned records with Fuel transactions.(All Fuels).When passed as ‘false’ the above condition will not be checked. (Both All Fuels and Non-Fuel) */
  fuelOnly?: string | null;
  /** Product group name */
  productGroupName?: string | null;
  /** Vehicle registration number embossed on the card */
  vehicleRegistrationNumber?: string | null;
  /** Flag to enable to get declined records */
  includeDeclines?: boolean | null;
  /** Card issuer name */
  cardIssuerName?: string | null;
  /**
   * Column list to be part of response, it can be 'All' to return all possible column. E.g. 'All'
   * To get specific columns pass multiple columns name separated by comma along with 'PayerNumber'. E.g. "PayerNumber,ProductCode"
   */
  columnList?: string;
}

export const recentTransactionReqSchema: Schema<RecentTransactionReq> = object({
  colCoCode: ['ColCoCode', nullable(number())],
  payerNumber: ['PayerNumber', nullable(string())],
  accountNumber: ['AccountNumber', optional(nullable(string()))],
  productCode: ['ProductCode', optional(nullable(string()))],
  purchasedInCountry: ['PurchasedInCountry', optional(nullable(string()))],
  cardPAN: ['CardPAN', optional(nullable(string()))],
  fromDateTime: ['FromDateTime', optional(nullable(string()))],
  toDateTime: ['ToDateTime', optional(nullable(string()))],
  transactionStatus: ['TransactionStatus', optional(nullable(string()))],
  fuelOnly: ['FuelOnly', optional(nullable(string()))],
  productGroupName: ['ProductGroupName', optional(nullable(string()))],
  vehicleRegistrationNumber: [
    'VehicleRegistrationNumber',
    optional(nullable(string())),
  ],
  includeDeclines: ['IncludeDeclines', optional(nullable(boolean()))],
  cardIssuerName: ['CardIssuerName', optional(nullable(string()))],
  columnList: ['ColumnList', optional(string())],
});
