/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import {
  SearchStatementOfAccount,
  searchStatementOfAccountSchema,
} from './searchStatementOfAccount';

export interface SearchStatementOfAccountResponse {
  /** Mandatory UUID (according to RFC 4122 standards) for requests and responses. This will be played back in the response from the req */
  requestId?: string;
  /** Indicates overall status of the request */
  status?: string;
  data?: SearchStatementOfAccount[];
  /** Current page */
  page?: number;
  /** Total Number of records in response */
  totalRecords?: number;
  /** Total number of pages available for the requested data */
  totalPages?: number;
  /** Number of records returned in the response */
  pageSize?: number;
}

export const searchStatementOfAccountResponseSchema: Schema<SearchStatementOfAccountResponse> = object(
  {
    requestId: ['RequestId', optional(string())],
    status: ['Status', optional(string())],
    data: ['Data', optional(array(lazy(() => searchStatementOfAccountSchema)))],
    page: ['Page', optional(number())],
    totalRecords: ['TotalRecords', optional(number())],
    totalPages: ['TotalPages', optional(number())],
    pageSize: ['PageSize', optional(number())],
  }
);
