/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface SearchSOAReq {
  /** Collecting Company Code of the selected payer. */
  colCoCode?: number | null;
  /**
   * Payer Number of the selected payer.
   * Optional if PayerId is passed else Mandatory.
   */
  payerNumber?: string | null;
  /**
   * Invoice number.
   * Optional.
   * This input is a search criterion, if given.
   */
  invoiceNumber?: string | null;
  /**
   * SOA searched from this date.
   * Optional.
   * This input is a search criterion, if given.
   * Date format: yyyy/MM/dd
   */
  fromDate?: string | null;
  /**
   * Invoice date searched until this date.
   * Optional.
   * This input is a search criterion, if given.
   */
  toDate?: string | null;
  /**
   * Invoice date search period. Valid values -
   * Last 7 days – Issued in last 7 days.
   * Last 30 days – Issued in last 30 days.
   * Last 90 days – Issued in last 90 days.
   * Optional.
   * This input is a search criterion, if given.
   */
  period?: number | null;
  /**
   * Date of invoicing.
   * Optional.
   * This input is a search criterion, if given.
   */
  invoiceDate?: string | null;
  /**
   * Possible options are:
   * 1.    StatementDate ASC
   * 2.    StatementDate DESC
   * Optional
   * Note:
   * This option uses a column name with a combination of “ASC or DESC” for sorting.
   * If only the column name is provided, it is sorted by ascending.
   * Sorting is allowed only ASC or DESC, If both provided in the input ASC will be taken as precedence.
   */
  invoiceStatus?: string[];
  /**
   * Possible options are:
   * 1.    StatementDate ASC
   * 2.    StatementDate DESC
   * Optional
   * Note:
   * This option uses a column name with a combination of “ASC or DESC” for sorting.
   * If only the column name is provided, it is sorted by ascending.
   * Sorting is allowed only ASC or DESC, If both provided in the input ASC will be taken as precedence.
   */
  sortBy?: number[];
  /**
   * Collecting Company Id  of the selected payer.
   * Optional if ColCoCode is passed else Mandatory.
   * Example:
   * 1-Philippines
   * 5-UK
   */
  colCoId?: number | null;
  /** Payer Id  of the selected payer. */
  payerId?: number | null;
}

export const searchSOAReqSchema: Schema<SearchSOAReq> = object({
  colCoCode: ['ColCoCode', optional(nullable(number()))],
  payerNumber: ['PayerNumber', optional(nullable(string()))],
  invoiceNumber: ['InvoiceNumber', optional(nullable(string()))],
  fromDate: ['FromDate', optional(nullable(string()))],
  toDate: ['ToDate', optional(nullable(string()))],
  period: ['Period', optional(nullable(number()))],
  invoiceDate: ['InvoiceDate', optional(nullable(string()))],
  invoiceStatus: ['InvoiceStatus', optional(array(string()))],
  sortBy: ['SortBy', optional(array(number()))],
  colCoId: ['ColCoId', optional(nullable(number()))],
  payerId: ['PayerId', optional(nullable(number()))],
});
