/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  StatementOfAccountRequestFilters,
  statementOfAccountRequestFiltersSchema,
} from './statementOfAccountRequestFilters.js';

export interface StatementOfAccountRequest {
  filters?: StatementOfAccountRequestFilters;
}

export const statementOfAccountRequestSchema: Schema<StatementOfAccountRequest> = object(
  {
    filters: [
      'Filters',
      optional(lazy(() => statementOfAccountRequestFiltersSchema)),
    ],
  }
);
