/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  TransactionFeesRequest,
  transactionFeesRequestSchema,
} from './transactionFeesRequest.js';

export interface TransactionFeesSummaryReq {
  filters?: TransactionFeesRequest;
}

export const transactionFeesSummaryReqSchema: Schema<TransactionFeesSummaryReq> = object(
  { filters: ['Filters', optional(lazy(() => transactionFeesRequestSchema))] }
);
