/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, nullable, object, optional, Schema } from '../schema.js';
import { CardExceptions, cardExceptionsSchema } from './cardExceptions.js';
import {
  TransactionExceptions,
  transactionExceptionsSchema,
} from './transactionExceptions.js';

export interface TransactionExceptionsResponse {
  cardExceptions?: CardExceptions[];
  transactionExceptions?: TransactionExceptions[] | null;
}

export const transactionExceptionsResponseSchema: Schema<TransactionExceptionsResponse> = object(
  {
    cardExceptions: [
      'CardExceptions',
      optional(array(lazy(() => cardExceptionsSchema))),
    ],
    transactionExceptions: [
      'TransactionExceptions',
      optional(nullable(array(lazy(() => transactionExceptionsSchema)))),
    ],
  }
);
