/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Accounts, accountsSchema } from './accounts';

export interface TransactionFeesRequest {
  /**
   * Collecting Company Id  of the selected payer.
   * Optional if ColCoCode is passed else Mandatory.
   * Example:
   * 1 for Philippines
   * 5 for UK
   */
  colCoId?: number | null;
  /**
   * Collecting Company Code (Shell Code) of the selected payer.
   * Mandatory for serviced OUs such as Romania, Latvia, Lithuania, Estonia, Ukraine etc. It is optional for other countries if ColCoID is provided.
   * Example:
   * 86 for Philippines
   * 5 for UK
   */
  colCoCode?: number | null;
  /**
   * Payer Id of the selected payer.
   * Optional if PayerNumber is passed else Mandatory
   * Example: 123456
   */
  payerId?: number | null;
  /**
   * Payer Number (Ex: GB000000123) of the selected payer.
   * Optional if PayerId is passed else Mandatory
   */
  payerNumber?: string | null;
  accounts?: Accounts[];
  /**
   * Card Id
   * Optional
   * When both Card Id and Card PAN are not present on request, the response will have all the fee items under the selected payer or account.
   * Example: 275549
   */
  cardId?: number | null;
  /**
   * Full Card PAN
   * Optional
   * When both Card Id and Card PAN are not present on request, the response will have all the fee items under the selected payer or account or card group.
   */
  cardPAN?: string | null;
  /**
   * Invoice status of the fee items
   * Mandatory
   * Possible options:
   * I - Invoiced
   * U – Un-Invoiced
   * A – All
   */
  invoiceStatus?: string | null;
  /**
   * Fee type group in under which the Fee item is generated.
   * Optional.
   * Allowed values:
   * - Account Charges
   * - Card Charges
   * - Others Charges
   */
  feeTypeGroup?: string | null;
  /**
   * Fee Type Id.
   * Optional.
   * Example:
   * 1. Simple Fee
   * 2. Card Event Fee
   * 3. Customer Event Fee
   */
  feeTypeId?: number | null;
  /**
   * Fee Item FromDate/Time
   * Should be with in last 24 months
   * Optional
   * Maximum of 210 days duration allowed per search, its configurable.
   * Format: yyyyMMdd
   */
  fromDate?: string | null;
  /**
   * Fee Item To Date/Time
   * Optional
   * When blank and FromDate is provided on the input, all fee items took place after the given from date/time should be returned. Note that the search is allowed for the maximum of 60 days. Hence if the FromDate is older than 60 days from current date then the fee items for 60 days from FromDate will be returned.
   * Format: yyyyMMdd
   */
  toDate?: string | null;
  /**
   * Fee items Period. This is ignored when FromDate/Todate is supplied on the request.
   * 1.    Last 7 Days
   * 2.    Last 30 Days
   * 3.    Last 90 Days
   * 4.    Last 180 Days
   * Example : Pass 1 for Last 7 days fee items
   */
  period?: number | null;
  /** True or False. When True, cancelled fee items are included on API response */
  includeCancelledItems?: boolean | null;
  /**
   * Product Id
   * Optional
   * Example: Sample list of product ids and description.
   * 100    Service fee
   * 102    Invoice production fee
   * 103    Account fee
   * 104    Transaction fee
   * 105    Card membership fee
   */
  productId?: number | null;
  /**
   * Product Code
   * Optional
   * Example:
   * 1. Service fee
   * 2. Invoice production fee
   * 3. Account fee
   * 4. Transaction fee
   * 5. Card membership fee
   */
  productCode?: string | null;
  /**
   * Line item description.
   * Optional
   * Minimum of 4 characters should be provided else not considered
   * Those fee items that have the entered value at any part of the line item description will be returned.
   */
  lineItemDescription?: string | null;
  /**
   * Allowed Sorting Options:
   * •    FeeDateAscending
   * •    FeeDateDescending
   * •    NetAmountAscending
   * •    NetAmountDescending
   * Optional.
   * Default: 1
   */
  sortOrder?: string | null;
  /** Page Number */
  currentPage?: number | null;
  /** Page Size – Number of records to show on a page */
  pageSize?: number | null;
}

export const transactionFeesRequestSchema: Schema<TransactionFeesRequest> = object(
  {
    colCoId: ['ColCoId', optional(nullable(number()))],
    colCoCode: ['ColCoCode', optional(nullable(number()))],
    payerId: ['PayerId', optional(nullable(number()))],
    payerNumber: ['PayerNumber', optional(nullable(string()))],
    accounts: ['Accounts', optional(array(lazy(() => accountsSchema)))],
    cardId: ['CardId', optional(nullable(number()))],
    cardPAN: ['CardPAN', optional(nullable(string()))],
    invoiceStatus: ['InvoiceStatus', optional(nullable(string()))],
    feeTypeGroup: ['FeeTypeGroup', optional(nullable(string()))],
    feeTypeId: ['FeeTypeId', optional(nullable(number()))],
    fromDate: ['FromDate', optional(nullable(string()))],
    toDate: ['ToDate', optional(nullable(string()))],
    period: ['Period', optional(nullable(number()))],
    includeCancelledItems: [
      'IncludeCancelledItems',
      optional(nullable(boolean())),
    ],
    productId: ['ProductId', optional(nullable(number()))],
    productCode: ['ProductCode', optional(nullable(string()))],
    lineItemDescription: ['LineItemDescription', optional(nullable(string()))],
    sortOrder: ['SortOrder', optional(nullable(string()))],
    currentPage: ['CurrentPage', optional(nullable(number()))],
    pageSize: ['PageSize', optional(nullable(number()))],
  }
);
