/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema';

export interface UsageSummary {
  /**
   * Transaction date.
   * The records will be sorted by this field in ascending order.
   * Format: yyyyMMdd
   */
  date?: string | null;
  /** Product Id */
  productId?: number | null;
  /** Client Product code */
  productCode?: string | null;
  /** Product name in English */
  productName?: string | null;
  /** Whether the product is fuel or non-fuel */
  isFuelProduct?: boolean | null;
  /** Site Group Id */
  siteGroupId?: number | null;
  /** Site Group Name */
  siteGroupName?: string | null;
  /** Total Volume */
  totalVolume?: number | null;
  /** Total Gross in Customer Currency */
  totalGross?: number | null;
  /** Total Net in Customer Currency */
  totalNet?: number | null;
  /** Customer Currency Code */
  currencyCode?: string | null;
  /** Customer Currency Symbol */
  currencySymbol?: string | null;
  /** Product group ID */
  productGroupID?: number | null;
  /** Product group Name */
  productGroupName?: string | null;
}

export const usageSummarySchema: Schema<UsageSummary> = object({
  date: ['Date', optional(nullable(string()))],
  productId: ['ProductId', optional(nullable(number()))],
  productCode: ['ProductCode', optional(nullable(string()))],
  productName: ['ProductName', optional(nullable(string()))],
  isFuelProduct: ['IsFuelProduct', optional(nullable(boolean()))],
  siteGroupId: ['SiteGroupId', optional(nullable(number()))],
  siteGroupName: ['SiteGroupName', optional(nullable(string()))],
  totalVolume: ['TotalVolume', optional(nullable(number()))],
  totalGross: ['TotalGross', optional(nullable(number()))],
  totalNet: ['TotalNet', optional(nullable(number()))],
  currencyCode: ['CurrencyCode', optional(nullable(string()))],
  currencySymbol: ['CurrencySymbol', optional(nullable(string()))],
  productGroupID: ['ProductGroupID', optional(nullable(number()))],
  productGroupName: ['ProductGroupName', optional(nullable(string()))],
});
