/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  VolumeBasedPricingRequest,
  volumeBasedPricingRequestSchema,
} from './volumeBasedPricingRequest.js';

export interface VolumeBasedPricingReq {
  filters?: VolumeBasedPricingRequest;
}

export const volumeBasedPricingReqSchema: Schema<VolumeBasedPricingReq> = object(
  {
    filters: ['Filters', optional(lazy(() => volumeBasedPricingRequestSchema))],
  }
);
