/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  VolumeBasedBonusResponse,
  volumeBasedBonusResponseSchema,
} from './volumeBasedBonusResponse.js';
import { Warning, warningSchema } from './warning.js';

export interface VolumeBasedBonusRes {
  /** Unique identifier for the request. This will be played back in the response from the request. */
  requestId?: string;
  /** Status of the request */
  status?: string;
  data?: VolumeBasedBonusResponse[];
  /**
   * A list of Warning entity.
   * This entity will hold the details of the scheduled System Outages of any dependent applications of this service.
   * Note: If there is no scheduled outage information available, in the configuration in AMS, for this service, this parameter won’t be present in output.
   */
  warnings?: Warning[];
}

export const volumeBasedBonusResSchema: Schema<VolumeBasedBonusRes> = object({
  requestId: ['RequestId', optional(string())],
  status: ['Status', optional(string())],
  data: ['Data', optional(array(lazy(() => volumeBasedBonusResponseSchema)))],
  warnings: ['Warnings', optional(array(lazy(() => warningSchema)))],
});
