/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  BonusConfiguration,
  bonusConfigurationSchema,
} from './bonusConfiguration.js';
import { BonusHistory, bonusHistorySchema } from './bonusHistory.js';
import { CurrentVolume, currentVolumeSchema } from './currentVolume.js';

export interface VolumeBasedBonusResponse {
  configuration?: BonusConfiguration[];
  currentPeriodConsumption?: CurrentVolume[];
  historicalBonusPaid?: BonusHistory[];
}

export const volumeBasedBonusResponseSchema: Schema<VolumeBasedBonusResponse> = lazy(
  () =>
    object({
      configuration: [
        'Configuration',
        optional(array(bonusConfigurationSchema)),
      ],
      currentPeriodConsumption: [
        'CurrentPeriodConsumption',
        optional(array(currentVolumeSchema)),
      ],
      historicalBonusPaid: [
        'HistoricalBonusPaid',
        optional(array(bonusHistorySchema)),
      ],
    })
);
