/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import {
  BonusConfiguration,
  bonusConfigurationSchema,
} from './bonusConfiguration.js';
import {
  PricingCurrentVolume,
  pricingCurrentVolumeSchema,
} from './pricingCurrentVolume.js';
import { PricingHistory, pricingHistorySchema } from './pricingHistory.js';
import { Warning, warningSchema } from './warning.js';

export interface VolumeBasedPricingResponse {
  configuration?: BonusConfiguration[];
  currentPeriodConsumption?: PricingCurrentVolume[];
  history?: PricingHistory[];
  /**
   * A list of Warning entity.
   * This entity will hold the details of the scheduled System Outages of any dependent applications of this service.
   * Note: If there is no scheduled outage information available, in the configuration in AMS, for this service, this parameter won’t be present in output.
   */
  warnings?: Warning[];
}

export const volumeBasedPricingResponseSchema: Schema<VolumeBasedPricingResponse> = lazy(
  () =>
    object({
      configuration: [
        'Configuration',
        optional(array(bonusConfigurationSchema)),
      ],
      currentPeriodConsumption: [
        'CurrentPeriodConsumption',
        optional(array(pricingCurrentVolumeSchema)),
      ],
      history: ['History', optional(array(pricingHistorySchema))],
      warnings: ['Warnings', optional(array(warningSchema))],
    })
);
