/**
 * Shell Data & Reporting APIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface Warning {
  /** A custom message giving the detailed outage information. The message will contain the duration and the reason for the outage. */
  message: string;
  /** Type of warning */
  type: string;
}

export const warningSchema: Schema<Warning> = object({
  message: ['Message', string()],
  type: ['Type', string()],
});
